test_workspace/BUILD
test_workspace/bo_test.bosatsu
tools/bosatsu.bzl

This allows us to write tests and run them with bazel.

Add initial bosatsu bazel test rule

---

build.sbt
core/src/main/scala/org/bykn/bosatsu/Codegen.scala
core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/Substitutable.scala
project/Dependencies.scala

This just bumps the deps in the sbt build.

Use cats 1.4.0

---

core/src/main/scala/org/bykn/bosatsu/Codegen.scala
core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/Expr.scala
core/src/main/scala/org/bykn/bosatsu/Infer.scala

this follows #47 in aligning the original AST with the rankN ast.

Add If node to Expr

---

core/src/main/resources/bosatsu/predef.bosatsu
core/src/main/scala/org/bykn/bosatsu/Declaration.scala
core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/Externals.scala
core/src/main/scala/org/bykn/bosatsu/Lit.scala
core/src/main/scala/org/bykn/bosatsu/Predef.scala
core/src/main/scala/org/bykn/bosatsu/Program.scala
core/src/main/scala/org/bykn/bosatsu/Statement.scala
core/src/main/scala/org/bykn/bosatsu/TypeRef.scala
core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala

Somehow when we pass direct values which are external vs wrapping them in lambdas, the result is different.

Add foldLeft and Evaluation test

---

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/Externals.scala
core/src/main/scala/org/bykn/bosatsu/Predef.scala
core/src/main/scala/org/bykn/bosatsu/rankn/DefinedType.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala

Add the Value ADT to make Evaluation safer

---

core/src/main/scala/org/bykn/bosatsu/Declaration.scala
core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/Lit.scala
core/src/main/scala/org/bykn/bosatsu/Predef.scala
core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala

Use BigInteger

---

.travis.yml
build.sbt
core/src/main/scala/org/bykn/bosatsu/Codegen.scala
core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
project/build.properties
project/plugins.sbt

set up code coverage, also test building the docs.

Set up codecov

---

core/src/main/scala/org/bykn/bosatsu/Declaration.scala
core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala

Fix the bug in if inference

---

core/src/main/resources/bosatsu/predef.bosatsu
core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/Parser.scala
core/src/main/scala/org/bykn/bosatsu/Predef.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
test_workspace/BUILD
test_workspace/euler1.bosatsu

This exercises bosatsu with project euler problem 1.
It seems our current evaluator is likely very slow. May need to actually think about performance sooner than I thought.

Add project euler problem 1

---

test_workspace/BUILD
test_workspace/euler2.bosatsu

add Euler problem 2

---

core/src/main/scala/org/bykn/bosatsu/Codegen.scala
core/src/main/scala/org/bykn/bosatsu/Declaration.scala
core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/Expr.scala
core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/Referant.scala
core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala

This is a TODO in #91 to make sure it is safe to expand the list literals.

Support fully qualified names in Expr

---

core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala
core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala

In the light of day, I'm not really sure why I have a certain custom method which can clearly be handled by recursion to a more tested code path.
Also added two additional law checks based on set theory of these matches.

Add some more tests, simplify a method

---

core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
core/src/main/scala/org/bykn/bosatsu/Referant.scala
core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala
core/src/main/scala/org/bykn/bosatsu/rankn/TypeEnv.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala

put the work from #103 into the compiler to error on non total matches in code.

Use match totality checking

---

core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala

this adds a positive and negative test using universal quantification to build a type equality.

Add an example of Leibniz type equality

---

core/src/main/scala/org/bykn/bosatsu/Parser.scala

found this turning the trials way up: one remaining case where we have an exception in the low-level unescape code.

Fix unescape bug

---

core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala
core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala

#109 is a real bug.
This shows the issue.
Repair is straightforward, but may break other properties.

Fix bug with list intersection

---

core/src/main/scala/org/bykn/bosatsu/Declaration.scala
core/src/main/scala/org/bykn/bosatsu/Parser.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala
core/src/test/scala/org/bykn/bosatsu/ParserTest.scala

Add tuple syntax parsing

---

core/src/main/scala/org/bykn/bosatsu/Declaration.scala

when I refactored this loop, I failed to update the variable in the loop, so the outer most Declaration was being filled in everywhere.

Fix the Declaration value in Expr

---

core/src/main/resources/bosatsu/predef.bosatsu
core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
core/src/main/scala/org/bykn/bosatsu/Predef.scala
core/src/main/scala/org/bykn/bosatsu/TypeRef.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
test_workspace/BUILD
test_workspace/euler5.bosatsu
test_workspace/euler6.bosatsu

solved Euler problems 5 and 6 and improve some error messages for the two most common cases (type mismatch and typo/undefined binding).

Better errors messages, and Project Euler 5 and 6

---

syntax/vim/bosatsu.vim

Add a basic vim syntax file

---

core/src/main/scala/org/bykn/bosatsu/Main.scala
core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
test_workspace/BUILD
test_workspace/euler7.bosatsu

Also do a minor clean up of the test output (no need to list missing tests if there are none missing).

Add Euler problem 7

---

core/src/main/scala/org/bykn/bosatsu/BindingStatement.scala
core/src/main/scala/org/bykn/bosatsu/Declaration.scala
core/src/main/scala/org/bykn/bosatsu/Program.scala
core/src/main/scala/org/bykn/bosatsu/Statement.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala
core/src/test/scala/org/bykn/bosatsu/ParserTest.scala

half of #140 
So far we are just handling parsing. A follow up will handle converting the pattern to a series of let bindings.

Add parser support for top level patterns

---

core/src/main/scala/org/bykn/bosatsu/Variance.scala
core/src/test/scala/org/bykn/bosatsu/VarianceTest.scala

this adds a variance type, but does not use it.
In support of #143 #144

Add Variance type to support variance inference

---

core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala
core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala

this turned up in #149 pulling out into its own PR.

fix a bug in freeTyVars in the ordering of the vars

---

core/src/main/scala/org/bykn/bosatsu/Codegen.scala
core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/ExportedName.scala
core/src/main/scala/org/bykn/bosatsu/NameKind.scala
core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/Referant.scala
core/src/main/scala/org/bykn/bosatsu/Wrappers.scala
core/src/main/scala/org/bykn/bosatsu/rankn/DefinedType.scala
core/src/main/scala/org/bykn/bosatsu/rankn/TypeEnv.scala

Add traverse instances for DefinedType and TypeEnv.

Add Traverse instances for DefinedType and TypeEnv

---

core/src/main/resources/bosatsu/predef.bosatsu
core/src/main/scala/org/bykn/bosatsu/Codegen.scala
core/src/main/scala/org/bykn/bosatsu/Declaration.scala
core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala
core/src/main/scala/org/bykn/bosatsu/DefStatement.scala
core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/ExportedName.scala
core/src/main/scala/org/bykn/bosatsu/Expr.scala
core/src/main/scala/org/bykn/bosatsu/NameKind.scala
core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
core/src/main/scala/org/bykn/bosatsu/Pattern.scala
core/src/main/scala/org/bykn/bosatsu/Predef.scala
core/src/main/scala/org/bykn/bosatsu/Program.scala
core/src/main/scala/org/bykn/bosatsu/RecursionKind.scala
core/src/main/scala/org/bykn/bosatsu/Statement.scala
core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala
core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
core/src/test/scala/org/bykn/bosatsu/DefRecursionCheckTest.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala
core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
core/src/test/scala/org/bykn/bosatsu/PatternTest.scala
core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
test_workspace/BUILD

close #87 
This is a significant addition that allows limited recursion where we can prove it will terminate.
cc @puffnfresh @snoble @avibryant 
Comments/code review welcome. Putting up the PR so I can see where the test coverage is missing. Will be nice to do a follow up PR that leverages recursion more (e.g. rewrite fold, review some of the existing project euler examples).

finish first draft of strutural recursion support

---

core/src/main/scala/org/bykn/bosatsu/Lit.scala
core/src/main/scala/org/bykn/bosatsu/Parser.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/ParserTest.scala

this is nice for writing big numbers.

Support _ as a separator in numbers

---

core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala

These are just to test the full stack of recursion checking, inference and evaluation.
cc @snoble who suggested some of these.

Add some more recursive evaluation tests

---

core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala
core/src/main/scala/org/bykn/bosatsu/DefStatement.scala
core/src/test/scala/org/bykn/bosatsu/DefRecursionCheckTest.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
docs/language_guide.md

Never let it be said that I let bugs in totality checking linger!
https://github.com/johnynek/bosatsu/pull/168#issuecomment-472724055
@snoble noticed that we are missing a requirement on recursion: that you cannot recurse on different variables. I added the test he suggested (which did infinitely loop for me when I checked it in Eval, and the test initially failed to disallow).
I'm very grateful to you @snoble for thinking about this, and noticing this problem.

Fix infinite loop snoble found

---

core/src/main/scala/org/bykn/bosatsu/Declaration.scala
core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/Pattern.scala
core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala
core/src/test/scala/org/bykn/bosatsu/ParserTest.scala

close #169 
This allows us to implement fib using recursion, not that one should, but it should be a legal program.

Add @ name bindings in patterns, close #169

---

core/src/main/resources/bosatsu/predef.bosatsu
core/src/main/scala/org/bykn/bosatsu/Predef.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala

Just PRing 2 and 3 to make sure this looks right before typing out the rest

Add uncurry2 and uncurry3

---

core/src/main/resources/bosatsu/predef.bosatsu
core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
core/src/main/scala/org/bykn/bosatsu/Predef.scala
core/src/main/scala/org/bykn/bosatsu/TypeRef.scala
core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala
core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala
core/src/test/scala/org/bykn/bosatsu/TypeRefTest.scala

This is the follow up to #167 that adds the methods.
The final step is to expand out literal dicts into calls to these methods.
part of #14

Add Dict fns to Predef

---

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/Predef.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala

This supports Dict in JSON generation. It also improve the json generation code by adding some helpers.
cc @wrobstory use bosatsu dicts to generate Json.

Support Dict in Json generation, improve Json

---

core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala
core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala

close #199 
No real bugs here, just somewhat wrong laws/shrinking/test code.

Fix #199, flakey tests in TypeTest

---

core/src/main/resources/bosatsu/predef.bosatsu
core/src/main/scala/org/bykn/bosatsu/Declaration.scala
core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala
core/src/main/scala/org/bykn/bosatsu/Expr.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala
core/src/test/scala/org/bykn/bosatsu/ParserTest.scala

close #188 
This will be pretty nice in a lot of cases, is easy to support.
What do you think @snoble ?

Add support for total patterns in lambdas

---

core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala

looks like #207 had an error: I missed a second place subs needed to become subs1
close #199 
for real this time.

fix 199 again

---

core/src/main/resources/bosatsu/predef.bosatsu
core/src/main/scala/org/bykn/bosatsu/Declaration.scala
core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/Predef.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala
core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala

Rename Tuple2 to TupleCons

---

core/src/main/resources/bosatsu/predef.bosatsu
core/src/main/scala/org/bykn/bosatsu/ListLang.scala
core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
core/src/main/scala/org/bykn/bosatsu/Predef.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala

address a few nits noticed in #217 
Hopefully make it a bit nicer to finish that PR.

Add clear_Dict and some other minor fixes

---

core/src/main/scala/org/bykn/bosatsu/Main.scala
core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/TestUtils.scala

close #219 
I reproduced the error, which was reversing the parsed package and the missing package. I also generalized and moved some code from Main into PackageMap so it was cleaner to reuse.

Fix exception in printing UnknownImportPackage

---

core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
core/src/main/scala/org/bykn/bosatsu/Pattern.scala
core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala

Fix some bad errors messages

---

core/src/main/scala/org/bykn/bosatsu/Main.scala
test_workspace/BUILD
test_workspace/List.bosatsu
test_workspace/Queue.bosatsu
test_workspace/TreeList.bosatsu
tools/bosatsu.bzl

fix #235 
Also fix a bug in list equality.

Improve test command

---

test_workspace/recordset.bosatsu

one last tweak. I may have gone too far.
this example would be nicer with type aliases. But that might just mean I'm doing this the wrong way

Go back to PairShape

---

cli/src/main/scala/org/bykn/bosatsu/TypedExprToProto.scala

This is trying to make the code more regular in advance of doing serialization of compiled packages which need to use the DAG approach used by `Type` for both `Pattern` and `TypedExpr`. Pattern depends on Strings and Types. TypedExpr depends on Strings, Types and Patterns.

improvements to the proto deserialization code

---

cli/src/main/scala/org/bykn/bosatsu/TypedExprToProto.scala
cli/src/test/scala/org/bykn/bosatsu/TestProtoType.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala

This adds pattern serialization. This is needed to serialize TypedExpr.
part of #54

Pattern to proto serialization

---

core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala

close #249 
close #246 
both of these are bugs in the laws, not bugs in the code, but they somewhat frequently waste a CI run. I shouldn't have waited so long to fix them. I'm sorry about that.

Fix 249 and 246, flaky tests

---

cli/src/main/protobuf/bosatsu/TypedAst.proto
cli/src/main/scala/org/bykn/bosatsu/Main.scala
cli/src/main/scala/org/bykn/bosatsu/TypedExprToProto.scala
cli/src/test/scala/org/bykn/bosatsu/TestProtoType.scala
core/src/main/scala/org/bykn/bosatsu/ExportedName.scala
core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/PackageName.scala
core/src/main/scala/org/bykn/bosatsu/Referant.scala
core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala
core/src/main/scala/org/bykn/bosatsu/rankn/DefinedType.scala
core/src/main/scala/org/bykn/bosatsu/rankn/TypeEnv.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala
core/src/test/scala/org/bykn/bosatsu/rankn/NTypeGen.scala
core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala

part of #54 
This is the last bit of proto serialization: compiled packages with all the ASTs inside suitable for evaluation or code generation.
There is not yet any testing, nor is it fully complete.

Proto support for compiled packages

---

WORKSPACE

this fixes the annoying reflection warning from protobuf.

Bump up rules_scala

---

cli/src/main/scala/org/bykn/bosatsu/Main.scala
test_workspace/BUILD
test_workspace/Dict.bosatsu
test_workspace/List.bosatsu
test_workspace/Queue.bosatsu
test_workspace/TreeList.bosatsu

I implemented a simple program and wanted some minor changes.
cc @snoble

Some improvements found playing with some example code

---

core/src/main/scala/org/bykn/bosatsu/Declaration.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
test_workspace/recordset.bosatsu

close #276 
I don't fully know what the bug was here, but since we added support for pattern lambdas, I could more directly use that functionality and share code paths. After doing that, the error seemed to disappear. Since this also removed one TODO I'll take it without looking too much deeper into the problem (probably kicking the can down the road).
cc @snoble

Fix bug with map_List/comprehension not working same

---

core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala
core/src/main/scala/org/bykn/bosatsu/Statement.scala

Separate the construction of the type environment from the let bindings. This is to set us up for #289 -- the reason is, we want to first see what types are in scope in a given file and then use that information to convert named arguments into unnamed argument calls and constructors.
Since named arguments are purely syntactical, we can do this before and independent of type-checking.

Separate TypeEnv and Lets construction in SourceConverter

---

.travis.yml

use openjdk rather than oraclejdk.

use openjdk8

---

core/src/main/scala/org/bykn/bosatsu/Fix.scala
core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/PackageMap.scala

If we want to use Fix in more places, it would be nice not to allocate each time we wrap and unwrap.

Use opaque trick for the Fix type

---

.travis.yml
core/src/test/scala/org/bykn/bosatsu/ParserTest.scala

Separate the scalajs build

---

core/src/main/scala/org/bykn/bosatsu/Declaration.scala
core/src/main/scala/org/bykn/bosatsu/Parser.scala
core/src/main/scala/org/bykn/bosatsu/Pattern.scala
core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala
core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala

Add record syntax parsing

---

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala

related to #118 
I just added this rule after seeing patterns like this show up due to how we add type information.
A better solution is probabably to optimize the typed trees, but since Evaluation ignores type information, this approach is easier to add something here.

Add an eta-conversion rule to Evaluation

---

core/src/main/scala/org/bykn/bosatsu/DefStatement.scala
core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala

Use Result in more of SourceConverter

---

core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala
core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala

Support creating structs with record syntax

---

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala

Fix the scoping issue with top-level lets

---

test_workspace/ApplicativeTraverse.bosatsu
test_workspace/BUILD
test_workspace/Option.bosatsu
tools/bosatsu.bzl

Need to add tests before I merge this.
There was also a type inference problem I will minimize when I tried to define it with:
```
def traverse_List -> Traverse[List]:
...
```
and that shouldn't infer differently.
also updated some bazel stuff needed to run bazel on my local machine.

Add an example of Applicative and Traverse with Bosatsu

---

test_workspace/BUILD
test_workspace/BinNat.bosatsu

This is a space efficient Nat implementation that I'm using to explore ergonomics around total programming.

Add BinNat example

---

core/src/main/scala/org/bykn/bosatsu/Predef.scala

I saw this TODO so I figured I'd do it quickly. There might be a smarter way to dedup but I'd suspect that wouldn't affect performance in a measurable way.

Solve imports from predef.bosatsu exports

---

core/src/main/scala/org/bykn/bosatsu/Predef.scala

Sort Predef imports

---

test_workspace/BinNat.bosatsu

Make use of TestSuite and write some law functions to make the tests less repetitive.

Improve the BinNat tests

---

core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala

Fix issue 330, incorrect error message for unknown names

---

core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala
core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala

close #329 
Add a region and message to all RecursionErrors.

Fix 329: improve printing of recursion errors

---

core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala
core/src/main/scala/org/bykn/bosatsu/Statement.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala

close #336 
partially addresses #340 for external def.

Check for external def shadowing and disallow it

---

core/src/main/scala/org/bykn/bosatsu/Pattern.scala
core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/TestUtils.scala

Show failures due to issue #345

Metavar escape issue bug (see 345)

---

core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala

Fix 350, require declared type params to be a superset

---

syntax/vim/bosatsu.vim
test_workspace/ApplicativeTraverse.bosatsu

This shows a pattern for implementing typeclasses that can have multiple different ways to define them.

expand the applicative example

---

.gitignore
build.sbt
core/src/main/scala/org/bykn/bosatsu/MainModule.scala
core/src/main/scala/org/bykn/bosatsu/MemoryMain.scala
core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
elmui/Makefile
elmui/elm.json
elmui/index.html
elmui/src/Main.elm
jsapi/src/main/scala/org/bykn/bosatsu/jsapi/JsApi.scala

This makes a simple in-browser version of the compiler.
The UI/UX is terrible (see below). It starts off way too small and it the error messages are very difficult to read but I will leave that to a future work.
cc @snoble

Add a Javascript API and simple elm app using it

---

.travis.yml
elmui/Makefile
elmui/build.sh

this is trying to get something I can deploy using travis ghpages deploy.

try to get Travis building the JS app

---

elmui/build.sh

looks like maybe there were more problems with setting up the ssh key.

print the checksum of the deploy key

---

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala

I hit a bug in #364 that exposed that we are not using type information at all in matching, contrary to what the code was implying (it was accessing it, but ignoring it).
Removing it removes one case where we had sys.error, which is valuable.

Simplify evaluation of match

---

cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala
elmui/elm.json

fix flakey test #376

---

elmui/elm.json
elmui/src/Main.elm

Since I don't know much at all about CSS, I thought I'd try elm-ui:
https://github.com/mdgriffith/elm-ui
the pitch is you don't need to understand CSS to make a decent UI.
I used this to make things look a bit better, and also add state so we can go forward and back between previously compiled data.
cc @snoble

Try using elm-ui

---

test_workspace/BUILD
test_workspace/Bool.bosatsu
test_workspace/List.bosatsu
test_workspace/euler1.bosatsu
test_workspace/euler2.bosatsu
test_workspace/euler5.bosatsu
test_workspace/euler7.bosatsu

using a loop in for_all is more efficient than fold because with a loop we can stop early.

Reduce duplication in example bosatsu code

---

test_workspace/BUILD
test_workspace/BinNat.bosatsu
test_workspace/Nat.bosatsu

This puts the Nat example code in its own file.
This is actually pretty nice code, IMO.

Move Nat code out of BinNat

---

cli/src/test/scala/org/bykn/bosatsu/TestProtoType.scala
core/src/main/scala/org/bykn/bosatsu/graph/Tree.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala

close #280 #371 
The problems here were not preventing some duplication of names in the generators.

Fix proto test flakiness

---

core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala

Fix an error message, see #382

---

core/src/main/scala/org/bykn/bosatsu/Declaration.scala
core/src/main/scala/org/bykn/bosatsu/Import.scala
core/src/main/scala/org/bykn/bosatsu/ListLang.scala
core/src/main/scala/org/bykn/bosatsu/Parser.scala
core/src/main/scala/org/bykn/bosatsu/Pattern.scala
core/src/test/scala/org/bykn/bosatsu/ParserTest.scala

fix the kinds of issues noted recently in #90 
https://github.com/johnynek/bosatsu/issues/90#issuecomment-549195941

Improve list syntax parsing

---

cli/src/main/scala/org/bykn/bosatsu/TypedExprToProto.scala
core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/ExportedName.scala
core/src/main/scala/org/bykn/bosatsu/Normalization.scala
core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/Referant.scala
core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala
core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala
core/src/main/scala/org/bykn/bosatsu/TypeRecursionCheck.scala
core/src/main/scala/org/bykn/bosatsu/VarianceFormula.scala
core/src/main/scala/org/bykn/bosatsu/rankn/ConstructorFn.scala
core/src/main/scala/org/bykn/bosatsu/rankn/DefinedType.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala
core/src/main/scala/org/bykn/bosatsu/rankn/TypeEnv.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala

addresses review comments @snoble left in #387

Make ConstructorFn a type

---

core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/TypedExprTest.scala
core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala

Fix lambda type collision with generic (390)

---

core/src/main/scala/org/bykn/bosatsu/Pattern.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala
core/src/test/scala/org/bykn/bosatsu/ParserTest.scala

close #254 
The issue is that we need to normalize unions on pattern parsing.

Fix flaky test issue 254

---

test_workspace/BinNat.bosatsu

this is another example of the fuel pattern #410 #406

Add fibonacci for BinNat

---

core/src/main/scala/org/bykn/bosatsu/Declaration.scala
core/src/main/scala/org/bykn/bosatsu/Parser.scala
core/src/test/scala/org/bykn/bosatsu/ParserTest.scala

close #408 
we want to have alignment like:
````
x = if y: z
else: w
````

Nicer parsing for if-elif-else #408

---

cli/src/test/scala/org/bykn/bosatsu/JsonTest.scala
core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/Json.scala
core/src/main/scala/org/bykn/bosatsu/Parser.scala
core/src/main/scala/org/bykn/bosatsu/Statement.scala
core/src/main/scala/org/bykn/bosatsu/Value.scala
core/src/main/scala/org/bykn/bosatsu/ValueToJson.scala
core/src/main/scala/org/bykn/bosatsu/rankn/TypeEnv.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/GenJson.scala
core/src/test/scala/org/bykn/bosatsu/JsonTest.scala
core/src/test/scala/org/bykn/bosatsu/rankn/NTypeGen.scala
jsapi/src/main/scala/org/bykn/bosatsu/jsapi/JsApi.scala

This is part of #412 
This improves the existing code but also does decoding and adds tests.
This is not yet wired into the CLI.

Support reading json to Values

---

bosatsuj
cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala
core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/Json.scala
core/src/main/scala/org/bykn/bosatsu/MainModule.scala
core/src/main/scala/org/bykn/bosatsu/ValueToJson.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala
core/src/test/scala/org/bykn/bosatsu/GenValue.scala
core/src/test/scala/org/bykn/bosatsu/JsonTest.scala
core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
core/src/test/scala/org/bykn/bosatsu/ValueTest.scala
core/src/test/scala/org/bykn/bosatsu/rankn/NTypeGen.scala
core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala
jsapi/src/main/scala/org/bykn/bosatsu/jsapi/JsApi.scala
test_workspace/Foo.bosatsu
tools/bosatsu.bzl

Support applying functions as json -> json transformations.

---

core/src/main/scala/org/bykn/bosatsu/SimpleStringPattern.scala
core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala
core/src/test/scala/org/bykn/bosatsu/SimpleStringPatternTest.scala
core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala

this improves string intersection and difference.
We use the same trick we use in lists: reverse the patterns if both end in literals so we can make progress there.

Improve string intersection and difference

---

cli/src/main/scala/org/bykn/bosatsu/PathModule.scala
core/src/main/scala/org/bykn/bosatsu/MainModule.scala

make typecheck output optional (439)

---

core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala

check struct correctness once in validate and don't repeatedly check inside intersection and difference.

Simplify TotalityCheck a bit

---

core/src/test/scala/org/bykn/bosatsu/pattern/StringSeqPatternSetLaws.scala

close #451 
I think the failures seem resolved.

add regression seen in 451

---

core/src/main/resources/bosatsu/predef.bosatsu
core/src/main/scala/org/bykn/bosatsu/Predef.scala

There is no reason range needs to be external. It could be written with Nats or using int_loop.
That is done here.

Make range a regular function

---

core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala

Make duplicate types or constructor names an error

---

.bazelrc.travis
WORKSPACE
project/build.properties

update to the latest rules_scala that works with bazel 1.2, update sbt.

Update build setup

---

docs/language_guide.md

Just fixing some typos

---

core/src/main/scala/org/bykn/bosatsu/Expr.scala
core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala
core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala
core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala
core/src/main/scala/org/bykn/bosatsu/UnusedLetCheck.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
core/src/test/scala/org/bykn/bosatsu/TypedExprTest.scala
core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala

Split Expr.Var into Expr.Global and Expr.Local

---

cli/src/main/scala/org/bykn/bosatsu/TypedExprToProto.scala
core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/Normalization.scala
core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala
core/src/test/scala/org/bykn/bosatsu/TypedExprTest.scala

Split TypedExpr.Var into Local and Global

---

core/src/main/scala/org/bykn/bosatsu/rankn/Ref.scala

This replaces the pattern of using an allocated object as a key in RefSpace and instead use a Long which is allocated with AtomicLong.
This makes it clearer the requirement instead of relying on properties of anonymous objects on the JVM. Also, Longs are cheaper and don't need GC.

Minor improvement of Ref/RefSpace

---

core/src/main/scala/org/bykn/bosatsu/Program.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala
core/src/test/scala/org/bykn/bosatsu/ProgramTests.scala

Add code to make top level lets unique

---

.travis.yml
core/src/main/scala/org/bykn/bosatsu/Matchless.scala
core/src/main/scala/org/bykn/bosatsu/Pattern.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Ref.scala
core/src/test/scala/org/bykn/bosatsu/MatchlessTests.scala

Add a matchless AST for easier compilation

---

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala

due to #487 and #490 top level names are unique and we resolve to Globals where possible (meaning top levels have no free variables).
This simplifies Evaluation because the captured scope only needs to have the locals, as it should be.

Simplify Evaluation using top-level uniqueness

---

.github/workflows/ci.yml
.travis.yml
build.sbt

Move most tests to github actions

---

core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala
core/src/main/scala/org/bykn/bosatsu/pattern/SeqPart.scala
core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala
core/src/test/scala/org/bykn/bosatsu/pattern/SetOpsLaws.scala

Fix (it seems) issue 497

---

cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala
cli/src/test/scala/org/bykn/bosatsu/codegen/python/CodeTest.scala
cli/src/test/scala/org/bykn/bosatsu/codegen/python/PythonGenTest.scala
core/src/main/scala/org/bykn/bosatsu/Identifier.scala
core/src/main/scala/org/bykn/bosatsu/Matchless.scala
core/src/main/scala/org/bykn/bosatsu/MatchlessToValue.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala

increase the test coverage of compiling to python.

Fix an issue with top-level recursives

---

core/src/main/resources/bosatsu/predef.bosatsu
core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala

Fix issue 130, allow use of tuple and list literals in Predef

---

bench/src/main/scala/org/bykn/bosatsu/TestBench.scala
core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala

during normalization, we repeatedly look at freeVars and profiling it shows up as one of the hottest methods.

Cache freeVarsDup for efficiency

---

.github/workflows/ci.yml
cli/src/test/scala/org/bykn/bosatsu/codegen/python/CodeTest.scala
cli/src/test/scala/org/bykn/bosatsu/codegen/python/PythonGenTest.scala
core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/MainModule.scala
core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala
core/src/test/scala/org/bykn/bosatsu/codegen/python/PythonGenTest.scala

this automatically generates `unittest` tests from the Bosatsu tests and runs them.
This allows us to test all the python code from the existing bosatsu tests.

Add test generation for python, and run them

---

.github/workflows/ci.yml
.travis.yml
build.sbt
build_native.sh
core/src/main/scala/org/bykn/bosatsu/CommentStatement.scala
core/src/main/scala/org/bykn/bosatsu/Declaration.scala
core/src/main/scala/org/bykn/bosatsu/DefStatement.scala
core/src/main/scala/org/bykn/bosatsu/FastparseCats.scala
core/src/main/scala/org/bykn/bosatsu/OptIndent.scala
core/src/main/scala/org/bykn/bosatsu/Parser.scala
core/src/main/scala/org/bykn/bosatsu/Statement.scala
project/Dependencies.scala
project/plugins.sbt

close #526 
This doesn't update fastparse, that is in a new issue: #545

update some dependencies

---

core/.js/src/main/scala/org/bykn/bosatsu/Platform.scala
core/.jvm/src/main/scala/org/bykn/bosatsu/Platform.scala
core/src/test/scala/org/bykn/bosatsu/DeclarationTest.scala
core/src/test/scala/org/bykn/bosatsu/JsonTest.scala
core/src/test/scala/org/bykn/bosatsu/LocationMapTest.scala
core/src/test/scala/org/bykn/bosatsu/MatchlessTests.scala
core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
core/src/test/scala/org/bykn/bosatsu/SourceConverterTest.scala
core/src/test/scala/org/bykn/bosatsu/ValueToDocTest.scala

Reduce size of scalajs scalachecks (see #548)

---

.github/workflows/ci.yml
.travis.yml
build.sbt
docs/src/main/paradox/design.md
docs/src/main/paradox/index.md
docs/src/main/paradox/language_guide.md
elmui/build.sh
project/plugins.sbt

part of #536 
This does not yet publish the documentation.
We need to do that (and then remove the old .md file to not have duplications).

Setup paradox for documentation generation

---

README.md
docs/src/main/paradox/generating_json.md
docs/src/main/paradox/getting_started.md
docs/src/main/paradox/index.md
docs/src/main/paradox/transpile_python.md

Improve docs some

---

cli/src/test/scala/org/bykn/bosatsu/codegen/python/CodeTest.scala
core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala
core/src/main/scala/org/bykn/bosatsu/Pattern.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/PatternTest.scala

close issue #573 
The issue was that we were just totally broken for pattern arguments to defs.

Fix issue 573, incorrect recursion checking with pattern arguments to defs

---

.github/workflows/ci.yml
bench/src/main/scala/org/bykn/bosatsu/parser/ParserBench.scala
build.sbt
parser/.js/src/main/scala/org/bykn/bosatsu/parser/BitSet.scala
parser/.jvm/src/main/scala/org/bykn/bosatsu/parser/BitSet.scala
parser/src/main/scala/org/bykn/bosatsu/parser/Parser.scala
parser/src/test/scala/org/bykn/bosatsu/parser/ParserTest.scala
project/Dependencies.scala

this is to address #545 
for a simple benchmark, this is as fast as fastparse:
```
[info] Do not assume the numbers tell you what you want them to tell.
[info] Benchmark                       Mode  Cnt  Score   Error  Units
[info] ParserBench.benchBigIntsFP     thrpt    3  1.588 ± 0.578  ops/s
[info] ParserBench.benchBigIntsLocal  thrpt    3  1.553 ± 0.489  ops/s
[success] Total time: 100 s (01:40), completed Oct 2, 2020 12:53:44 PM
```

Add parsing module

---

README.md

It's a bit ridiculous, but I can never read past these without a PR.

Minor typo in Readme

---

parser/src/main/scala/org/bykn/bosatsu/parser/Parser.scala
parser/src/test/scala/org/bykn/bosatsu/parser/ParserTest.scala

this simplifies Expectation.unify and makes the laws around composition of oneOf clearer.

Add a separate Fail parser to make composition laws a bit clearer

---

core/src/main/scala/org/bykn/bosatsu/Pattern.scala
core/src/test/scala/org/bykn/bosatsu/PatternTest.scala

fix issue 577

---

bench/src/main/scala/org/bykn/bosatsu/parser/ParserBench.scala
parser/.js/src/main/scala/org/bykn/bosatsu/parser/BitSet.scala
parser/.jvm/src/main/scala/org/bykn/bosatsu/parser/BitSet.scala
parser/src/main/scala/org/bykn/bosatsu/parser/Parser.scala
parser/src/test/scala/org/bykn/bosatsu/parser/ParserTest.scala

adds some test coverage, make some changes based on using it to parse bosatsu.

Updates to the new parser library

---

core/src/main/scala/org/bykn/bosatsu/Declaration.scala
core/src/main/scala/org/bykn/bosatsu/Operators.scala

I tried to tackle a TODO, but I could not. I added more comments on the matter. It's a bit subtle unfortunately and probably needs a bit more work to fix.

Improve parsing of operators marginally

---

build.sbt
core/src/test/scala/org/bykn/bosatsu/Gen.scala
core/src/test/scala/org/bykn/bosatsu/rankn/NTypeGen.scala

I like this plugin in general (it allows using total pattern matches in for comprehensions) but it may also improve performance marginally in a few cases.

use better monadic for

---

build.sbt
project/Dependencies.scala

Remove munit for now

---

cli/src/main/scala/org/bykn/bosatsu/TypedExprToProto.scala
project/plugins.sbt

Update scalapb to the latest released version

---

build.sbt
core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala
core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
core/src/main/scala/org/bykn/bosatsu/MemoryMain.scala
core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala
core/src/main/scala/org/bykn/bosatsu/TypeRef.scala
core/src/main/scala/org/bykn/bosatsu/UnusedLetCheck.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala
core/src/main/scala/org/bykn/bosatsu/rankn/DefinedType.scala
core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
jsapi/src/main/scala/org/bykn/bosatsu/jsapi/JsApi.scala

Update kind projector and use new syntax

---

core/src/main/scala/org/bykn/bosatsu/LocationMap.scala

noticed this when using non-expanded tabs.

Fix showing a pointer to code having a tab

---

core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/TestUtils.scala

close #653 
Somehow, it wasn't until recently that I noticed that bad types give really terrible error messages.

Fix 653, error message on unknown type names

---

core/src/main/scala/org/bykn/bosatsu/Declaration.scala
core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala
core/src/main/scala/org/bykn/bosatsu/Operators.scala
core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala
core/src/main/scala/org/bykn/bosatsu/Statement.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala
core/src/test/scala/org/bykn/bosatsu/ParserTest.scala

close #652 
I may revert this later, but I wanted to experiment with it a bit in a toy project

Add support for the left apply syntax idea

---

project/plugins.sbt

Revert "Update compilerplugin, scalapb-runtime to 0.10.10"

---

project/plugins.sbt

Revert "Update sbt-protoc to 1.0.0"

---

core/src/main/scala/org/bykn/bosatsu/Pattern.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
core/src/test/scala/org/bykn/bosatsu/PatternTest.scala
core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
test_workspace/BinNat.bosatsu
test_workspace/TreeList.bosatsu
test_workspace/euler4.bosatsu

close #623 
This harmonizes bosatsu patterns more with python patterns.

Use as instead of @, fix 623

---

bosatsuj
build.sbt
build_native.sh
core/src/main/scala/org/bykn/bosatsu/Matchless.scala

the idea is to avoid making an Always node if the condition has no side effects.

Improve Matchless for last branch of match

---

cli/src/main/scala/org/bykn/bosatsu/Main.scala
cli/src/main/scala/org/bykn/bosatsu/PathModule.scala
cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala
cli/src/test/scala/org/bykn/bosatsu/TestProtoType.scala
project/Dependencies.scala

Update cats effect 3

---

.github/workflows/ci.yml
build.sbt
project/plugins.sbt

Use 0.11.1 scalapb compiler plugin

---

.github/workflows/ci.yml
build.sbt
core/.jvm/src/main/scala/org/bykn/bosatsu/Par.scala
core/src/main/scala/org/bykn/bosatsu/MainModule.scala
core/src/main/scala/org/bykn/bosatsu/Pattern.scala
core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala
core/src/main/scala/org/bykn/bosatsu/Test.scala
core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala
core/src/main/scala/org/bykn/bosatsu/ValueToDoc.scala
core/src/main/scala/org/bykn/bosatsu/VarianceFormula.scala
core/src/main/scala/org/bykn/bosatsu/graph/Memoize.scala
core/src/main/scala/org/bykn/bosatsu/rankn/DefinedType.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala
core/src/test/scala/org/bykn/bosatsu/JsonTest.scala
core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala
core/src/test/scala/org/bykn/bosatsu/pattern/SetOpsLaws.scala
core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala

since I can't compile the cli module on my M1, I just did core. :/

Remove some unused values in core

---

core/src/test/scala/org/bykn/bosatsu/TypedExprTest.scala

Add a couple of normalization tests

---

core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
core/src/main/scala/org/bykn/bosatsu/TypedExprNormalization.scala

This should increase parallelism since optimization/normalization is a purely local operation after type checking.

Parallelize package normalization

---

core/src/main/scala/org/bykn/bosatsu/Matchless.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala

I was inspecting the generated python and trying to remove things that shouldn't be needed.
This makes some significant improvements, but there is still a bit more to go (although, maybe it doesn't matter too much).

Improve the Matchless and Python generated code a bit

---

core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala
core/src/main/scala/org/bykn/bosatsu/TypedExprNormalization.scala

Remove unused private names, close #766

---

.github/workflows/ci.yml
.github/workflows/upload_asset.yml
base/src/main/scala/org/bykn/bosatsu/Macro.scala
bosatsuj
build.sbt
build_native.sh
cli/src/main/scala/org/bykn/bosatsu/PathModule.scala
cli/src/test/scala/org/bykn/bosatsu/JsonTest.scala
cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala
cli/src/test/scala/org/bykn/bosatsu/TestProtoType.scala
core/src/main/scala/org/bykn/bosatsu/MatchlessToValue.scala
core/src/main/scala/org/bykn/bosatsu/NameKind.scala
core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala
core/src/main/scala/org/bykn/bosatsu/Statement.scala
core/src/main/scala/org/bykn/bosatsu/TypeRef.scala
core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala
core/src/main/scala/org/bykn/bosatsu/Variance.scala
core/src/main/scala/org/bykn/bosatsu/VarianceFormula.scala
core/src/main/scala/org/bykn/bosatsu/pattern/NamedSeqPattern.scala
core/src/main/scala/org/bykn/bosatsu/pattern/SeqPattern.scala
core/src/main/scala/org/bykn/bosatsu/pattern/Splitter.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala
core/src/main/scala/org/bykn/bosatsu/rankn/TypeEnv.scala
core/src/test/scala/org/bykn/bosatsu/DeclarationTest.scala
core/src/test/scala/org/bykn/bosatsu/GenJson.scala
core/src/test/scala/org/bykn/bosatsu/LocationMapTest.scala
core/src/test/scala/org/bykn/bosatsu/ValueTest.scala
core/src/test/scala/org/bykn/bosatsu/pattern/SeqPatternTest.scala
elmui/Makefile
jsapi/src/main/scala/org/bykn/bosatsu/jsapi/JsApi.scala

this removes the 2.12 build, which I think is fine since this is a compiler, not a library.

Use scala 2.13

---

core/src/main/scala/org/bykn/bosatsu/ExportedName.scala
core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
test_workspace/bazel_deps_api.bosatsu

error on private type leaks (issue #782)

---

build.sbt

this has a native mac arm binary.

Use protoc 3.19.1

---

.github/workflows/ci.yml
.github/workflows/upload_asset.yml
build.sbt

Use scala 2.13.7

---

core/src/main/scala/org/bykn/bosatsu/Declaration.scala
core/src/main/scala/org/bykn/bosatsu/Parser.scala
core/src/test/scala/org/bykn/bosatsu/ParserTest.scala

support syntax like:
```
x = (
y = 3
y
)
```

Allow indentation in nested blocks

---

.gitignore
.scalafmt.conf
core/src/main/scala/org/bykn/bosatsu/Kind.scala
core/src/test/scala/org/bykn/bosatsu/KindParseTest.scala

Add a representation of Kind

---

core/src/main/scala/org/bykn/bosatsu/ListOrdering.scala
core/src/main/scala/org/bykn/bosatsu/graph/Dag.scala
core/src/main/scala/org/bykn/bosatsu/graph/Toposort.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala
core/src/test/scala/org/bykn/bosatsu/MonadGen.scala
core/src/test/scala/org/bykn/bosatsu/graph/DagTest.scala
core/src/test/scala/org/bykn/bosatsu/graph/ToposortTest.scala

this is intended to be used for #121 in order to build tags of variance dependencies within a given defined type.

Add Dagify and improve Toposort types

---

core/src/main/scala/org/bykn/bosatsu/TypeRef.scala
core/src/main/scala/org/bykn/bosatsu/TypeRefConverter.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala
core/src/test/scala/org/bykn/bosatsu/ParserTest.scala

Rename TypeLambda to TypeForAll

---

core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/PackageError.scala
core/src/main/scala/org/bykn/bosatsu/Shape.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala

add some better error messages for shape errors

---

core/src/main/scala/org/bykn/bosatsu/Kind.scala
core/src/main/scala/org/bykn/bosatsu/PackageError.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala

Improve Kind check Error classes

---

core/src/main/scala/org/bykn/bosatsu/Kind.scala
core/src/test/scala/org/bykn/bosatsu/KindParseTest.scala
core/src/test/scala/org/bykn/bosatsu/OrderingLaws.scala

close #955 
I can't easily make the code stack safe, but I did make it stack safe enough to make it run for a long time before finally erroring, which convinces me this kind is just not anywhere close to realistic.
So, I kept the safer (but still not safe) code but limit our tests to only huge not astronomical kinds.

Fix issue 955 from recurring

---

cli/src/main/scala/org/bykn/bosatsu/Main.scala
core/src/main/scala/org/bykn/bosatsu/MainModule.scala

currently we get a stack trace on `type-check` or `test` if there are no inputs. Instead we should just print a sane error and return an error code. We don't need a stack trace for that.
We should only have stack traces if the compiler has a bug.

Improve main on no inputs

---

core/src/test/scala/org/bykn/bosatsu/KindParseTest.scala

this doesn't really exercise anything but the test filtering very big examples.

Remove too big kind from test

---

syntax/vscode/bosatsu/.vscode/launch.json
syntax/vscode/bosatsu/.vscodeignore
syntax/vscode/bosatsu/CHANGELOG.md
syntax/vscode/bosatsu/README.md
syntax/vscode/bosatsu/language-configuration.json
syntax/vscode/bosatsu/package.json
syntax/vscode/bosatsu/syntaxes/bosatsu.tmLanguage.json
syntax/vscode/bosatsu/vsc-extension-quickstart.md

close #957 
Seems to work well enough for me. Can always be improved.

Add basic textmate grammar

---

core/src/main/resources/bosatsu/predef.bosatsu

part of #966 
Just making sure we don't have any problem typing the `build_List` function.

Add build_List foldr_List

---

.github/workflows/ci.yml
build.sbt
cli/src/main/scala/org/bykn/bosatsu/PathModule.scala
cli/src/test/scala/org/bykn/bosatsu/JsonTest.scala
cli/src/test/scala/org/bykn/bosatsu/TestProtoType.scala
cli/src/test/scala/org/bykn/bosatsu/codegen/python/CodeTest.scala
cli/src/test/scala/org/bykn/bosatsu/codegen/python/PythonGenTest.scala
core/src/test/scala/org/bykn/bosatsu/CollectionUtilsTest.scala
core/src/test/scala/org/bykn/bosatsu/DeclarationTest.scala
core/src/test/scala/org/bykn/bosatsu/FreeVarTest.scala
core/src/test/scala/org/bykn/bosatsu/Gen.scala
core/src/test/scala/org/bykn/bosatsu/IntLaws.scala
core/src/test/scala/org/bykn/bosatsu/JsonTest.scala
core/src/test/scala/org/bykn/bosatsu/LocationMapTest.scala
core/src/test/scala/org/bykn/bosatsu/MatchlessTests.scala
core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
core/src/test/scala/org/bykn/bosatsu/PatternTest.scala
core/src/test/scala/org/bykn/bosatsu/SourceConverterTest.scala
core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala
core/src/test/scala/org/bykn/bosatsu/TypeRefTest.scala
core/src/test/scala/org/bykn/bosatsu/TypedExprTest.scala
core/src/test/scala/org/bykn/bosatsu/ValueTest.scala
core/src/test/scala/org/bykn/bosatsu/ValueToDocTest.scala
core/src/test/scala/org/bykn/bosatsu/codegen/python/PythonGenTest.scala
core/src/test/scala/org/bykn/bosatsu/graph/DagTest.scala
core/src/test/scala/org/bykn/bosatsu/graph/ToposortTest.scala
core/src/test/scala/org/bykn/bosatsu/pattern/SeqPatternTest.scala
core/src/test/scala/org/bykn/bosatsu/pattern/SetOpsLaws.scala
core/src/test/scala/org/bykn/bosatsu/pattern/StringSeqPatternSetLaws.scala
core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala

Upgrade to scala 2.13.11

---

cli/src/main/scala/org/bykn/bosatsu/Main.scala
cli/src/main/scala/org/bykn/bosatsu/PathModule.scala
cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
test_workspace/recordset.bosatsu

Fix issue 1023

---

core/src/main/resources/bosatsu/predef.bosatsu
core/src/main/scala/org/bykn/bosatsu/Parser.scala
core/src/main/scala/org/bykn/bosatsu/TypeParser.scala
test_workspace/BuildLibrary.bosatsu

another change related to #1026

Change fn type parsing

---

core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala

Make sure 932 is tested

---

build.sbt
core/src/main/scala/org/bykn/bosatsu/DirectEC.scala
core/src/main/scala/org/bykn/bosatsu/KindFormula.scala
core/src/main/scala/org/bykn/bosatsu/ParallelViaProduct.scala
core/src/main/scala/org/bykn/bosatsu/Shape.scala
core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala
core/src/main/scala/org/bykn/bosatsu/TypeRef.scala
core/src/main/scala/org/bykn/bosatsu/TypedExprNormalization.scala
core/src/main/scala/org/bykn/bosatsu/Variance.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala
core/src/main/scala/org/bykn/bosatsu/graph/Toposort.scala
core/src/main/scala/org/bykn/bosatsu/pattern/SeqPart.scala
core/src/main/scala/org/bykn/bosatsu/pattern/SeqPattern.scala
core/src/main/scala/org/bykn/bosatsu/pattern/Splitter.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Ref.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala
core/src/test/scala/org/bykn/bosatsu/pattern/SeqPatternTest.scala

Bump to scala 2.13.12

---

core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala

Tried to improve efficiency by:
1. preserving NonEmptyList information
2. moving Right cases before Left
3. remove some allocations

Some minor Infer code cleanups

---

core/src/main/scala/org/bykn/bosatsu/KindFormula.scala
core/src/main/scala/org/bykn/bosatsu/rankn/DefinedType.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala
core/src/test/scala/org/bykn/bosatsu/KindFormulaTest.scala
core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala

Fix issue 1082

---

core/src/main/scala/org/bykn/bosatsu/pattern/SeqPattern.scala
core/src/test/scala/org/bykn/bosatsu/pattern/SeqPatternTest.scala

fix seqpattern intersection commutative issue 1091

---

core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/PackageCustoms.scala
core/src/main/scala/org/bykn/bosatsu/PackageError.scala
core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
core/src/main/scala/org/bykn/bosatsu/PackageName.scala
core/src/main/scala/org/bykn/bosatsu/Pattern.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala
core/src/test/scala/org/bykn/bosatsu/PackageTest.scala
test_workspace/BuildExample.bosatsu
test_workspace/List.bosatsu

Error on unused imports in Bosatsu packages

---

core/src/main/scala/org/bykn/bosatsu/pattern/SeqPattern.scala
core/src/test/scala/org/bykn/bosatsu/pattern/SeqPatternTest.scala

Fix issue 1104

---

build.sbt
core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala
core/src/main/scala/org/bykn/bosatsu/pattern/SeqPart.scala
core/src/main/scala/org/bykn/bosatsu/pattern/SeqPattern.scala
core/src/main/scala/org/bykn/bosatsu/set/PartialRel.scala
core/src/main/scala/org/bykn/bosatsu/set/Rel.scala
core/src/main/scala/org/bykn/bosatsu/set/Relatable.scala
core/src/main/scala/org/bykn/bosatsu/set/SetOps.scala
core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala
core/src/test/scala/org/bykn/bosatsu/pattern/SeqPatternTest.scala
core/src/test/scala/org/bykn/bosatsu/pattern/StringSeqPatternSetLaws.scala
core/src/test/scala/org/bykn/bosatsu/set/RelLaws.scala
core/src/test/scala/org/bykn/bosatsu/set/SetOpsLaws.scala

This is code from a project developed with @non several years ago.
The code contains laws for set algebra, a relation type useful for comparing sets, and a recursive algorithm to compute relations by decomposing unions written as lists.
I think this could help me improve the pattern totality checking.

Add set relation code from a private project.

---

bosatsuj
cli/src/main/scala/org/bykn/bosatsu/CodeGenWrite.scala
cli/src/main/scala/org/bykn/bosatsu/PathModule.scala
core/src/main/scala/org/bykn/bosatsu/Import.scala
core/src/main/scala/org/bykn/bosatsu/MainModule.scala
core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/PackageCustoms.scala
core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala
core/src/test/scala/org/bykn/bosatsu/TypedExprTest.scala
test_workspace/Bool.bosatsu

This allows you to print out compiled bosatsu code. This is useful for inspecting what the compiler has produced already shows a few issues I should improve.

add a show command

---

core/src/main/scala/org/bykn/bosatsu/Json.scala

minor nit after playing with generating some json.

Make empty json array two chars

---

core/src/main/scala/org/bykn/bosatsu/pattern/SeqPattern.scala
core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala
core/src/test/scala/org/bykn/bosatsu/set/SetOpsLaws.scala

Fix totality check issue 1121

---

.gitignore
core/src/main/scala/org/bykn/bosatsu/MainModule.scala
jsui/src/main/scala/org/bykn/bosatsu/jsui/Action.scala
jsui/src/main/scala/org/bykn/bosatsu/jsui/Store.scala
jsui/src/main/scala/org/bykn/bosatsu/jsui/View.scala

Add show to the web ui

---

jsui/src/main/scala/org/bykn/bosatsu/jsui/App.scala
jsui/src/main/scala/org/bykn/bosatsu/jsui/View.scala
project/Dependencies.scala

Update to ff4s 0.23.0

---

jsui/src/main/scala/org/bykn/bosatsu/jsui/Store.scala
project/Dependencies.scala

Update ff4s to 0.24.0

---

.github/workflows/ci.yml
cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala
core/src/main/scala/org/bykn/bosatsu/DefStatement.scala
core/src/main/scala/org/bykn/bosatsu/MainModule.scala
core/src/main/scala/org/bykn/bosatsu/Statement.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala
test_workspace/Prog.bosatsu
test_workspace/Prog.bosatsu_eval
test_workspace/Prog.bosatsu_externals
test_workspace/ProgExt.py

The Prog type here is based on the scala implementation of ToyIO in this PR:
https://github.com/johnynek/bosatsu/pull/1162
The idea was to write that type where I have the compiler to help, then port it to a python loop.

Add Prog example for effectful programs

---

core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala

this shows the https://github.com/johnynek/bosatsu/issues/1233 failure.
For some reason, the existential case works, I bet due to the special casing of substitution that was added.

fix some existential type unification cases

---

.github/workflows/ci.yml
project/build.properties

thanks to help from @eed3si9n I got this fixed.
replaces #1237

Bump to sbt 1.10.4

---

core/src/main/scala/org/bykn/bosatsu/codegen/clang/Code.scala
core/src/test/scala/org/bykn/bosatsu/codegen/clang/CodeTest.scala

continue adding C syntax structures.

continue C code generator

---

core/src/main/scala/org/bykn/bosatsu/codegen/Idents.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala
core/src/test/scala/org/bykn/bosatsu/codegen/IdentsTest.scala
core/src/test/scala/org/bykn/bosatsu/codegen/python/PythonGenTest.scala

this code will be useful for C code generation.

Factor Ident escaping from python code generation

---

core/src/main/scala/org/bykn/bosatsu/Matchless.scala
core/src/main/scala/org/bykn/bosatsu/MatchlessToValue.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala
core/src/test/scala/org/bykn/bosatsu/MatchlessTests.scala

we know finally we can't have recursive values that aren't functions, but the Matchless code does not give that invariant.
This changes the code so backends don't need to handle general recursive lets, which wouldn't be easy in C, and in python was only working because actually the recursions were functions.

Simplify Matchless.Let around recursion

---

cli/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala
cli/src/test/scala/org/bykn/bosatsu/codegen/python/PythonGenTest.scala
core/src/main/scala/org/bykn/bosatsu/FfiCall.scala
core/src/main/scala/org/bykn/bosatsu/MainModule.scala
core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangGen.scala
core/src/main/scala/org/bykn/bosatsu/codegen/clang/Code.scala
core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala
core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
core/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala

I tested that the generated code that it compiles. I need to add a CI test that the code compiles, but for now it was manual.

Test c generation of all predef

---

.github/workflows/ci.yml
.gitignore
c_runtime/Makefile
c_runtime/bosatsu_runtime.h
c_runtime/test.c
cli/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala
core/src/main/scala/org/bykn/bosatsu/MainModule.scala
core/src/main/scala/org/bykn/bosatsu/Matchless.scala
core/src/main/scala/org/bykn/bosatsu/codegen/Transpiler.scala
core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangGen.scala
core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangTranspiler.scala
core/src/main/scala/org/bykn/bosatsu/codegen/clang/Code.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonTranspiler.scala
core/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala

This generates C for all the test_workspace. It tests that it compiles, but it does not yet compile warning-free or produce runnable code until the predef and runtime are implemented.

test compilation of generated c

---

core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangGen.scala
core/src/main/scala/org/bykn/bosatsu/codegen/clang/Code.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala
core/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala

this ports the python code over to C and it seems to compile

Implement searchList in C

---

cli/src/test/scala/org/bykn/bosatsu/codegen/python/CodeTest.scala
core/src/main/scala/org/bykn/bosatsu/Matchless.scala
core/src/main/scala/org/bykn/bosatsu/MatchlessToValue.scala
core/src/main/scala/org/bykn/bosatsu/Pattern.scala
core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangGen.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala

This also improves the python code generation somewhat after looking more at the generated code.

Pass in MatchString if a string match must be total (which we already knew)

---

core/src/main/scala/org/bykn/bosatsu/Package.scala
core/src/main/scala/org/bykn/bosatsu/PackageMap.scala

Add methods to remove unused values (treeshake)

---

.github/workflows/ci.yml
c_runtime/Makefile
c_runtime/boehm_example.c

add an example of building a program using boehm gc and compiling on mac and linux

boehm gc example

---

core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangGen.scala
core/src/main/scala/org/bykn/bosatsu/codegen/clang/Code.scala

any C compiler would definitely optimize these away, but some code paths were generating `if (1) { } else { }` which was distracting when you read the generated code.

Simplify some if/else generation in C

---

c_runtime/bosatsu_ext_Bosatsu_l_Predef.h
c_runtime/bosatsu_ext_Bosatsu_l_Prog.c
c_runtime/bosatsu_ext_Bosatsu_l_Prog.h
c_runtime/bosatsu_runtime.c
c_runtime/bosatsu_runtime.h
cli/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala
core/src/main/scala/org/bykn/bosatsu/TypeName.scala
core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangGen.scala
core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangTranspiler.scala
core/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala
test_workspace/Prog.bosatsu
test_workspace/Prog.bosatsu_eval
test_workspace/Prog.bosatsu_externals
test_workspace/ProgExt.py

```
oscar@patricks-air bosatsu % c_out/test_exe
10
9
8
7
6
5
4
3
2
1
done
args = c_out/test_exe
```
This can run the basic count down program in Prog::main

Implement the main loop in C

---

c_runtime/bosatsu_ext_Bosatsu_l_Predef.c
c_runtime/bosatsu_ext_Bosatsu_l_Predef.h
c_runtime/bosatsu_runtime.c
c_runtime/bosatsu_runtime.h
core/src/main/resources/bosatsu/predef.bosatsu
core/src/main/scala/org/bykn/bosatsu/Predef.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala
test_workspace/PredefTests.bosatsu

obvious and useful function when writing little programs to read from arguments and do some math

Add string_to_Int to predef

---

core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala

suggest `recur` when functions use `match` and recur.

---

c_runtime/bosatsu_ext_Bosatsu_l_Predef.c
c_runtime/bosatsu_ext_Bosatsu_l_Predef.h
cli/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala
core/src/main/resources/bosatsu/predef.bosatsu
core/src/main/scala/org/bykn/bosatsu/Predef.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala
core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
test_workspace/Bar.bosatsu
test_workspace/PatternExamples.bosatsu
test_workspace/recordset.bosatsu

Rename string_Order_fn to cmp_String, close #1277

---

core/src/main/scala/org/bykn/bosatsu/PackageError.scala
core/src/main/scala/org/bykn/bosatsu/TypeName.scala

Improve unimported type message, close 1174

---

cli/src/test/scala/org/bykn/bosatsu/codegen/python/CodeTest.scala

Try to fix 1285

---

core/src/main/scala/org/bykn/bosatsu/MemoryMain.scala
core/src/main/scala/org/bykn/bosatsu/Package.scala

so we can implement write methods

use State instead or Reader (Kleisli) in MemoryMain

---

cli/src/main/scala/org/bykn/bosatsu/IOPlatformIO.scala
cliJS/src/main/scala/org/bykn/bosatsu/Fs2PlatformIO.scala
core/src/main/scala/org/bykn/bosatsu/Json.scala
core/src/main/scala/org/bykn/bosatsu/MainModule.scala
core/src/main/scala/org/bykn/bosatsu/MemoryMain.scala
core/src/main/scala/org/bykn/bosatsu/PlatformIO.scala
core/src/main/scala/org/bykn/bosatsu/library/Command.scala
core/src/main/scala/org/bykn/bosatsu/library/LibConfig.scala
core/src/main/scala/org/bykn/bosatsu/library/Libraries.scala
core/src/main/scala/org/bykn/bosatsu/library/ProtoJsonReaders.scala
core/src/main/scala/org/bykn/bosatsu/library/Version.scala
core/src/main/scala/org/bykn/bosatsu/tool/Output.scala

this is the start to being able to use the cli to create library configurations and eventually publish libraries.
It's a long road.
part of #1152

Add Library cli options

---

build.sbt
project/plugins.sbt

Bump to 2.13.16

---

core/src/main/scala/org/bykn/bosatsu/library/ApiDiff.scala

the api diff problem uses align quite a lot, but I only realized it late in writing the code. Use it more.

Use Align in ApiDiff

---

core/src/main/scala/org/bykn/bosatsu/MainModule.scala
core/src/main/scala/org/bykn/bosatsu/tool/CompilerApi.scala
core/src/main/scala/org/bykn/bosatsu/tool/PackageResolver.scala

the idea here is to make it easier to call these functions from the lib subcommand

Refactor CompilerApi out of MainModule

---

.github/workflows/ci.yml
cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala
core/src/main/scala/org/bykn/bosatsu/MainModule.scala
core/src/main/scala/org/bykn/bosatsu/codegen/Transpiler.scala
core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangGen.scala
core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangTranspiler.scala
core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonTranspiler.scala
core/src/main/scala/org/bykn/bosatsu/hashing/Algo.scala
core/src/main/scala/org/bykn/bosatsu/hashing/Hashed.scala
core/src/main/scala/org/bykn/bosatsu/library/Command.scala
core/src/main/scala/org/bykn/bosatsu/library/DecodedLibrary.scala
core/src/main/scala/org/bykn/bosatsu/library/DecodedLibraryWithDeps.scala
core/src/main/scala/org/bykn/bosatsu/library/LibConfig.scala
proto/src/main/protobuf/bosatsu/TypedAst.proto

This does not yet plumb through all code to actually call the build, but it sets up the options parsing.

Add lib build command
