johnynek/bosatsu

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
Without this change you get the somewhat cryptic
```
[error] (run-main-0) java.util.NoSuchElementException: key not found: (PackageName(NonEmptyList(Foo, S, Example)),fold)
```
instead of
```
[error] (run-main-0) org.bykn.bosatsu.EvaluationException: Missing External defintion of 'Foo/S/Example fold'. Check that your 'external' parameter is correct.
```
I should proooobably add tests
=> Better error messages for when external definitions are missing

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Substitutable.scala, core/src/main/scala/org/bykn/bosatsu/Type.scala, core/src/test/scala/org/bykn/bosatsu/TypeTest.scala
This is part of #9 but not the whole story.
It adds TypeLambda back to the Type AST, which is what Scheme really is. It does not yet remove Scheme since we are using in many places, but Scheme should be a synonym for Type.
This does not yet do anything in Infer with TypeLambda, which I think has to be done if we are going to handle unifying them at all. I think the unification should be obvious: you can only unify with a Var or another TypeLambda, and if you unify with the TypeLambda you replace the unbound parameter to a common value.
@snoble can you take a look and let me know what you think if you have time? I think you are more concerned with semantics and syntax than typechecking, but I'd be interested in your code review.
=> Add TypeLambda to the Type AST

core/src/main/scala/org/bykn/bosatsu/Infer.scala, core/src/main/scala/org/bykn/bosatsu/Type.scala, core/src/test/scala/org/bykn/bosatsu/InferTest.scala
I want `forall a. Int` to unify with `Int` and other simplifications of type lambdas.
=> Add some more unification tests

core/src/main/scala/org/bykn/bosatsu/Codegen.scala, core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Expr.scala, core/src/main/scala/org/bykn/bosatsu/Infer.scala, core/src/test/scala/org/bykn/bosatsu/InferTest.scala
We want to allow annotating types for both documentation but also improving error reporting in type checking.
This adds two expressions: annotating an expression, and annotating the argument to a lambda.
We don't currently use it at all.
=> Add annotated expression nodes

core/src/main/scala/org/bykn/bosatsu/rankn/Ref.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Tc.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Term.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNTcTest.scala
This is a direct port of the haskell code in the paper in #5 
This is not yet used in any bosatsu code. We will also need to follow the paper to expand how to handle matches, which are not included in the simple language used in the appendix of the paper.
Rather than using IO, I introduce a RefSpace monad to support mutable references, which their algorithm uses.
=> Add an implementation of rank-n type inference

core/src/main/scala/org/bykn/bosatsu/rankn/Tc.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Term.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNTcTest.scala
This implements the suggestion from the paper on handling matches.
Here we only support if, not a full match, which requires us to think about pattern matches.
Some form of pattern matching will be next.
=> Add If support to rank-n types

core/src/main/scala/org/bykn/bosatsu/rankn/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Tc.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Term.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNTcTest.scala
This continues following the paper into section 7 where patterns and matching is discussed.
Unfortunately the paper does not include inference rules for a match statement, and my current understanding is only enough to follow the directions in the paper, not prove results. So, I can't yet see the right way to extend the inference rules for the case of a match.
In the case of `if` we know the type of the argument, but in the case of `match` we have to infer the type of the argument.
In addition to the above difficulty, we also have the problem that parametric type constructors `struct Option[a](a: a)` cannot be supported currently because we have no way to remember if we have an `Option[Int]` or `Option[String]`. For this, we need, I think a TypeApply term in the rankn.Type ast.
=> Add Pattern to rank-n support

core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNTcTest.scala
I added a test for the main event here: higher ranked inference.
I stumbled implementing this because I created an invalid `ForAll` node. By testing the invariant on construction, we avoid creating bad nodes which allowed me to solve the issue.
I'd like to check these invariants in the types and not have to resort to a runtime check.
=> Add higher rank test

core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
1. rename Tc to Infer, which isn't a perfect name, but is better.
2. Replace the error type from String to an ADT enumerating the possible kinds of errors.
=>  Rename rankn.Tc to rankn.Infer

core/src/main/scala/org/bykn/bosatsu/PackageName.scala, core/src/main/scala/org/bykn/bosatsu/Type.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
This is a step in merging rank n inference to be the only system.
The approach is to match `Expr[A]` up to `Term` and replace the `Type` with `rankn.Type`
=> Use PackageName in rankN defined types

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Expr.scala, core/src/main/scala/org/bykn/bosatsu/Infer.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/TypeRef.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
Moving towards replacing the old type inference, we need a way to fully annotate the types of the inferred expressions.
The old approach was to embed the annotation on each expression node on the tag. It is not 100% clear this was ever totally good enough for us.
We need to know the types during evaluation if we want to use compact representations of structs and enums, because we need to know what index a field name corresponds to, or what name a variant index refers to.
Section 8 of then rankn paper (see #5) discusses type directed translation. In this approach, when we infer, we also emit a new AST that is fully annotated such that inference of types is trivial. This is what we want to move towards, but to do this, it seemed likely we would need to implement type annotations in …
=> Add type annotation to patterns

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/Expr.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/main/scala/org/bykn/bosatsu/TypeRef.scala
closes #6 
The hard work was already done in the #34 rankn work. Currently old infer still ignores this information, but we are plumbing it all the way through here.
=> Use type annotations in defs in converting to Expr

core/src/main/scala/org/bykn/bosatsu/Expr.scala, core/src/main/scala/org/bykn/bosatsu/Lit.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
This, I think, what the paper calls type directed translation. It is not totally clear on the details, and I am foggy on a few bits here.
The idea is to convert Expr to a fully typed (or trivially type-inferred) AST. I have followed section 8 mostly in the paper. I have not fully grokked section 4.8.
Currently, I'm only checking the returned types of the AST, not that they are fully typed in sane ways. We need more tests here.
I also wanted to depart from the paper because it uses a single AST but promises the resulting ast is typed. I wanted to have a different AST so we can see from the type it must be fully typed. They make an off-hand suggestion about adding two new nodes. I couldn't see fully what they meant by that. I added one node and was able to get my very simple tests to pass. …
=> convert Expr to TypedExpr

core/src/main/scala/org/bykn/bosatsu/ExportedName.scala, core/src/main/scala/org/bykn/bosatsu/Import.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/InferTest.scala
imports and name mappings were added when I worked on packages, but they were never really well plumbed back down in the conversion from the syntactic representation to the expression representation.
There are TODOs around this in then rankn infer. To clean this up, I first pulled the import code out of the top level (package, which kind of sees everything) and make them independent. Then we can make statements require an import map to convert statements into a program.
We don't do any of this yet, but it is plumbed through and ready.
=> Add ImportMap

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Expr.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
Previously, we ignored type annotations in defs. Since rankn types landed we don't, but it does not work for generics:
What is?
```
def indent(x: a) -> a:
x
```
We currently translate it into an `AnnotatedLambda` with input type annotation of `TyVar(Var.Bound("a"))`. The problem is, that's an unbound variable.
Bounds should only be inside an outer `ForAll` now or they are not valid.
Maybe a solution is in the Infer code when we encounter an unbound Bound as an input type annotation, we introduce either a skolem variable or a meta variable (I'm not really sure which is correct). Ideally, we want to see that `identity: forall a. a -> a`.
Clearly we need more tests on the code.
related to #32
=> Generics in defs don't work

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala
This adds support for python's ternary syntax, which is a bit odd, but does read well and has the virtue of us being closer to python, which is a goal.
this sketches part of the solution to add optionally indented items.
Relates to #16
=> Support python ternary syntax

core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
actually, #84 isn't a bug.
The error message isn't clear, but if you are unifying, for instance `a = List[a]`, then you need an infinite type, this does not unify.
I wrote the wrong type annotations in #84, but assumed it was a bug with the compiler.
Related to #4
=> fix non-bug number 84

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/NameKind.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, test_workspace/euler1.bosatsu
This PR is based on a comment I heard in a talk on the Unity programming language. The idea is that an interpreter can partially evaluate a fair amount statically by currying the environment. By doing this, you can build and cache everything you need in one advance pass, then pass the environments along, which are the things that change and probably are not useful to cache.
This seems to cut the bazel bosatsu test time way down (maybe 3x faster, and note we are still paying JVM startup cost, so it may be more than that if we carefully account for the improvement).
cc @snoble if you have time to take a look at this approach.
=> Use partial evaluation to go faster

core/src/main/resources/bosatsu/predef.bosatsu, core/src/main/scala/org/bykn/bosatsu/Codegen.scala, core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Expr.scala, core/src/main/scala/org/bykn/bosatsu/ListLang.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/main/scala/org/bykn/bosatsu/Predef.scala, core/src/main/scala/org/bykn/bosatsu/Referant.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala, test_workspace/euler1.bosatsu, test_workspace/euler2.bosatsu
closes #13 
This adds the construction, not pattern matching, for list literals.
There are two issues:
1. the parsing is still not correct since I can't parse function application in lists: `[ Foo(a, b), c ]` does not parse. I'm not sure why. It seems to be failing when it gets to the `,`.
2. we effectively need macros here, but I have no way to be sure I reference a particular fully qualified function. It may be that we need to expand Expr to have point to imported names instead of just Var that refers to the current environment.
=> Add list literal constructors

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, test_workspace/euler2.bosatsu
This allows a syntax similar to python:
```
match foo:
[]: "empty"
[head]: "1 item"
[head, *middle, last]: "2 or more"
```
Unlike python, I currently allow multiple `*a` patterns, and I allow `*_` when you don't care to bind a set of items.
The matching algorithm goes like this:
1. if the first item in the pattern is not prefixed with `*`, match the head item according to normal pattern matching
2. if the first item in the pattern is a splice `*`, then take the tail of the pattern which has size N, then match it against at most N items from the list, this match is done in reverse order. If that matches, then we take the prefix that is unmatched and bind it to the splice.
closes #94
=> implement list patterns

core/src/main/resources/bosatsu/predef.bosatsu, core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Externals.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/Predef.scala, core/src/main/scala/org/bykn/bosatsu/Test.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/PackageTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala, test_workspace/bo_test.bosatsu, test_workspace/euler1.bosatsu, test_workspace/euler2.bosatsu, test_workspace/test.bosatsu
@avibryant asked, and then I subsequently noticed that since we were allowing recursive (though not infinite) data types, that is enough to be able to put a type on a fixed point combinator, which allows it to be expressed and breaks totality.
Original comment here:
https://github.com/johnynek/bosatsu/pull/100#discussion_r228962619
The fix here is to add a check that types form a DAG. This makes it impossible to define the list type in bosatsu, but that isn't too much of a loss (since we add it with an external type). This also requires changing the built in testing framework from a tree to an optionally 3 level construct.
This is much more limited than before, but I think we have regained totality.
=> Ban Recursive Structs

core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala, core/src/main/scala/org/bykn/bosatsu/rankn/DefinedType.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/main/scala/org/bykn/bosatsu/rankn/TypeEnv.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala
When we expanded the power of the patterns the naive exhaustivity checking was removed because it wouldn't work.
Since then, we have actually been rolling with no match exhaustivity checking.
This adds code to check all patterns are exhaustive. It *seems* that with the current pattern language, we actually don't need to typecheck to do totality checking, which is interesting. That might be a good property to maintain (and maybe is always, or almost always true...)
This turns out to be a bit tricky and I had to derive some formulas, which I just left in the comments. I have pretty good tests of the checker, but will see a better test when I wire it into the compiler.
=> Add TotalityCheck and tests

core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
Rather than report an issue, I just figured I'd open a PR showing the error.
It seems we are partially shadowing, so either the constructors for matching, or the type name is not getting shadowed.
=> Bug with name shadowing of Predef

core/src/main/scala/org/bykn/bosatsu/Lit.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
close #35 for real.
Two issues:
1.  bug was a scalacheck misuse around bad shrinking.
2. actual bugs in some escaped strings.
I fixed both issues and ran 500k tests and it passed. The escaping/unescaping can probably be optimized. This copies most of pythons escaping syntax:
copied from here:
https://docs.python.org/3/reference/lexical_analysis.html
The `\N{unicode name}` is not supported (yet) since it seems we need a database for that.
=> Fix flakey string tests

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/Program.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
Still left to do:
1. generate patterns for parsing testing
2. support reading a pattern in the parser
part of #19 
Since we already have #107 this should just work once we support it in the parser.
=> Support destructuring assignment in Declaration

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/ListLang.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
This is the parsing side to #112 which closes out #19 
Since we already have totality checking, this is perfectly safe since it is just a match statement internally, and we already needed to check match statements.
Testing the parser changes here made me see I was misusing cuts, which should probably very rarely appear in combinators since you don't know how they might be used. The cuts were making it impossible to do a simple parsing of patterns as binding targets (on the left of an equals) since the basic approach uses backtracking.
The performance is not stellar, but we do through insanely brutal randomly generated code at the parser.
=> Parse pattern match assignment

core/src/main/resources/bosatsu/predef.bosatsu, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Predef.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, test_workspace/BUILD, test_workspace/euler3.bosatsu
This adds a general intLoop (total) function to aid in common looping cases, and uses it to implement rangeFold (which is basically the same as range followed by fold, but definitely never materializes the list in memory).
intLoop is a bit specialized, but surely terminates. Hopefully that will be universal for Int based recursions that we need to run.
=> Add Euler 3 using intLoop and rangeFold in Predef

test_workspace/BUILD, test_workspace/euler4.bosatsu
This works, but it shows that actually evaluation is pretty slow. Running for `999` rather than `99` takes more than 1 minute, which should only be evaluating 1M candidates.
Evaluation currently uses cats Eval, which is not the optimal way to run these computations, pretty soon performance may matter. My biggest concern is that we may be re-evaluating things since Eval is not memoizing by default.
Anyway. This shows a less trivial example than the previous ones. Also, it is interesting that int_loop came up so many times here. This looks like a pretty critical function.
=> Add Euler problem 4

core/src/main/scala/org/bykn/bosatsu/LocationMap.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
When we moved to the rankn type inference, we lost the tracking of regions where types are inferred.
Here is an example now with an error added to euler4.bosatsu
```
in file: test_workspace/euler4.bosatsu, package Euler/Four, type Bosatsu/Predef#String does not unify with type Bosatsu/Predef#Int
54|  res
55|
56|fail = 1.add("2")
^^^
```
This is far from perfect. We need to solve #132 to improve some error messages.
Also, and open issue is how to test this best. I think the scala compiler just uses golden data tests where they commit what they expect the output to be.
=> Track regions when doing type inference

core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
The issue is, if we have something we declare to be generic, we currently can unify it with a concrete type, which is not what we want that syntax to mean.
It seems like we should be using skolem variables here, but if we do that, predef fails to compile.
=> Add a failing test showing incorrect unification of generic

core/src/main/scala/org/bykn/bosatsu/DefStatement.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
close #124 
Allow a syntax like this:
```
def foo:
x = 42
y = 36
x.times(y)
```
=> Support zero argument defs

core/src/main/scala/org/bykn/bosatsu/DefStatement.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala
After #131 was thought to be fixed:
I get:
```
[info] - test inference with some defined types *** FAILED *** (170 milliseconds)
[info]   in file: <unknown source>, package Test, type Opt does not unify with type $f
[info]   Region(414,418) (RankNInferTest.scala:98)  
```
In this example, it is trying to unify `Opt` with a skolem variable `f`.
It's not really clear what is going on, but I think the code should typecheck. 
The fix in #131 was not correct. Here we revert that and add a few more tests to exercise use of universal quantification (generics) in syntax.
I'm much more confident in the current approach.
=> Second attempt at dealing with generic types in defs

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/Program.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/PatternTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
evaluation part of #140 follow on to #141 
I found a bug in evaluation that this triggered that requires a code branch to be lazy which was being strict. That was probably really hurting performance.
=> support evaluation of top level pattern matches

core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
The paper we derive the type system from does not directly address user defined types. So, there is a question of what special casing of the function types need to be done for user defined types.
This PR adds some tests that show two good statements (I think) that are ruled out, despite them being safe, which I think could be allowed if we tracked variance of structs (see #143 #106).
Basically, any test that passes with a function type should pass if we replace the function with a wrapper of function: `struct FnWrapper(fn: a -> b)`, but this test shows two examples of that not being true.
=> Add variance tests, show some issues

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/ExportedName.scala, core/src/main/scala/org/bykn/bosatsu/NameKind.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/Program.scala, core/src/main/scala/org/bykn/bosatsu/Referant.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala, core/src/main/scala/org/bykn/bosatsu/rankn/DefinedType.scala, core/src/main/scala/org/bykn/bosatsu/rankn/TypeEnv.scala, core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala
The idea here is to keep track of annotations on user defined types. The use cases are for variance (#144 #143 ) and also possibly kind inference #121
=> Add a type parameter to DefinedType to annotate Bosatsu type parameters

core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala
It occurred we could give a more complete law for freeTyVars which would have caught the error I caught last night.
=> Add two more tests on freeTypeVars

core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/Tree.scala, core/src/main/scala/org/bykn/bosatsu/TypeRecursionCheck.scala, core/src/test/scala/org/bykn/bosatsu/TreeTest.scala
This is a step in addressing #148 
Here we factor the code so that the circularity checking is in a single file. The next step is to run variance inference, and then using the variance annotations, ignore cycles that are covariant or phantom, and only bad contravariant and invariant loops.
=> Refactor circularity check

core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/Program.scala, core/src/main/scala/org/bykn/bosatsu/Tree.scala, core/src/main/scala/org/bykn/bosatsu/VarianceFormula.scala, core/src/main/scala/org/bykn/bosatsu/rankn/ParsedTypeEnv.scala, core/src/main/scala/org/bykn/bosatsu/rankn/TypeEnv.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
Once again, the pattern of using a type parameter that changes at different phases becomes useful. After we have parsed the syntax, we have one notion of what types are present, but after we have fully inferred and resolved imports we have another notion.
This change allows us to express that change pretty cleanly. It also makes it explicit that we only have two kinds of changes to the type environment from parsing after imports: defined types, and external definitions.
=> Add ParsedTypeEnv

core/src/main/scala/org/bykn/bosatsu/NameKind.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/TypeRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/VarianceFormula.scala
This wires in the code, and lines up the types, to infer variance properly.
This could make some programs not compile if there are bugs in variance inference. A following PR will correctly use the variance to look for allowable a cases of recursion in types.
=> Infer variance, but ignore it for now

core/src/main/scala/org/bykn/bosatsu/VarianceFormula.scala, core/src/test/scala/org/bykn/bosatsu/VarianceFormulaTest.scala
Assume that external structs are invariant (a worst case).
We could imagine adding syntax to denote variance, but following scala we can let the unannotated mean invariant, which shouldn't be backwards incompatible.
=> Fix a bug around external types and variance inference

core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/TypeRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/VarianceFormula.scala, core/src/main/scala/org/bykn/bosatsu/graph/Paths.scala, core/src/main/scala/org/bykn/bosatsu/graph/Tree.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/TypeRecursionCheckTest.scala, core/src/test/scala/org/bykn/bosatsu/graph/TreeTest.scala
This PR attempts to address #148 undoing #102.
The check currently is rather restrictive. The graph of types must:
1. form a DAG *excluding self references*.
2. for each type, all self referential loops must be via covariant or phantom variance paths.
This allows us to write all the kinds of types that I think we want, and are also safe: List, Tree, etc... while banning types that can be used to allow recursion, e.g. types associated with the y-combinator.
A follow up to this PR will be making List a normal type again, and not an external def, but I will keep the special python inspired syntax we have for lists.
=> Allow basic restricted recursion in types.

core/src/main/resources/bosatsu/predef.bosatsu, core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/Predef.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, docs/language_guide.md
This reverts the list change in #102 
now that we can support recursive types in covariant position, no need to have List as an external type.
=> Make List a native, non-external type again

core/src/main/scala/org/bykn/bosatsu/Referant.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/main/scala/org/bykn/bosatsu/rankn/TypeEnv.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
see #106 and #144 
This makes variance information available to inference, but we do not yet use it.
In a follow up PR we can stop specializing on Type.Fun in inference and instead use the variance of each type parameter of a given user defined type.
=> Plumb variance information through the inference

core/src/main/scala/org/bykn/bosatsu/Codegen.scala, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/NameKind.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/test/scala/org/bykn/bosatsu/CodegenTest.scala
relates to #161 
This weakens the view, in the types, of what inference sees to be clear you don't see the full bodies of the expressions you import.
This cleans up things a bit, and hopefully makes it easier to add separate compilation since now we could add not only parsed inputs but previously inferred interface files as well.
=> Define Package.Interface to avoid using all of the package

core/src/main/resources/bosatsu/predef.bosatsu, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala, core/src/test/scala/org/bykn/bosatsu/TypedExprTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
Filter the environment we capture before building a Lambda function. This seems to help somewhat, and is just good for GC also. A real code generator would need to do this.
Also, I noticed on a test I added, performance of foldLeft is about 4-5x better if I only recur on the two variables that are changing, and let fn be captured by a closure. That is likely a general strategy: minimize the function size for recursive functions while we don't have any optimization of multiple argument functions (so they are implemented via currying).
=> filter free vars in lambda

core/src/main/scala/org/bykn/bosatsu/Lit.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
this is part of #14 
This is only doing the parsing. It does not address adding to Declaration the code to represent literal dicts.
=> Add code for parsing python dicts

core/src/main/resources/bosatsu/predef.bosatsu, core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/DefStatement.scala, core/src/main/scala/org/bykn/bosatsu/Program.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/test/scala/org/bykn/bosatsu/DefRecursionCheckTest.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/PackageTest.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala, docs/language_guide.md
as @avibryant suggested on this thread:
https://github.com/johnynek/bosatsu/pull/164#issuecomment-472038378
it is a bit awkward to have `def` and `recursive def`. There is the verbosity problem, but also the problem that scoping rules were different in each case. This PR changes that: all defs have the most restrictive rules. This rules out a few older programs that worked that shadowed def names inside themselves, which is no longer allowed.
We still require a `recur` to signify a recursive match, which helps readability for humans, but also simplifies the matching algorithm somewhat.
I think the change which harmonizes the rules is valuable.
cc @snoble as usual, I would welcome your comments.
=> Unify def and recursive def

core/src/main/scala/org/bykn/bosatsu/Codegen.scala, core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Expr.scala, core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
close #175 
Remove If, it is a special case of Match which we should optimize anyway.
=> Remove Expr.If and TypedExpr.If

core/src/main/scala/org/bykn/bosatsu/RecursionKind.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
1. we were not unifying the inferred type with the variable we created. This should be a bug in some cases.
2. after #172 all defs were marked recursive, but they are slightly more expensive to evaluate. This detects is a let is truly recursive and labels it as such, so it is accurate in TypedExpr.
=> Recursive inference improvements

README.md, core/src/main/resources/bosatsu/predef.bosatsu, core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/ListLang.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/Predef.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, test_workspace/euler1.bosatsu, test_workspace/euler2.bosatsu, test_workspace/euler4.bosatsu, test_workspace/euler5.bosatsu
close #99 
To solve this I had to fix a few lurking parser bugs, but the diff is small enough that I'm leaving it combined. There is no chance I don't want to have list/for comprehensions to match python.
They make several existing problems a bit more elegant and certainly looking more like python.
These are implemented basically as macros in the expansion from syntax (Declaration) into the lambda calculus based Expr. A more ambitious language might expose a means to make user defined macros which could do expansion into the Expr graph.
=> Get list comprehensions working

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
This is a follow up to #88 . In that PR, we didn't implement that partial evaluation strategy in matching, so matches were still pretty expensive.
This PR fully inspects the patterns once for the code path, and generates the functions to transform then environment one time. This should help in complex match situations, and at least harmonizes the approach.
PS: I think this partial evaluation is closer to real compilation, so it is helpful to see an example of pattern matching implemented in this way.
=> Use partial evaluation in pattern matching

core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala, core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala
I hope this makes #147 rare enough that we never see it again.
I minimized the failure down and it appears to be an issue with ill-typed patterns. Any change I could find from the minimized pattern passed, so I think it is mostly leveraging a union between incompatible types and list subtraction from wildcard.
I made a fix to the test that should reduce false positives, hopefully to a very small number.
closes #147
=> improve issue 147

.gitignore, build.sbt, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Json.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/main/scala/org/bykn/bosatsu/StringUtil.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/JsonTest.scala, project/Dependencies.scala
close #139 
Here we use our current escaping rules, but json has different rules than python, so we have to build a different escaping table.
I verified the fix with Jawn.
Long term, maybe we should just use Jawn directly, but Jawn is very focused on parsing fast, where as here I think we really care what the Json looks like and not so much about being as fast as possible, so for now I didn't make that change.
cc @snoble
=> Fix Json escaping (#139)

core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/TypeRef.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
close #182 
The issue here is this code here:
https://github.com/johnynek/bosatsu/pull/173
We used subsumption checking, where we should be using unify. The difference is that subsumption assumes you are dealing with full types, not metavariables (type unknowns) that have yet to be solved. Instead, before we fully solve for the type, we should unify the solved type with itself in recursive cases.
This fixes the issue reported above.
Along the way I considerably improved the printing of types in the compiler errors, which was hampering my ability to see what the problem was here.
=> fix an issue with nested def type inference

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/ListLang.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala
this closes #14 cc @wrobstory 
This reuses the code for handling the list comprehension syntax so we get a fair amount of reuse. There is no notion of flattening here like there is for lists, and I think that's the right call. There is also no notion (currently) of pattern matching on dicts. If you want to do that, convert them to lists via .items.
On a personal note, it feels exciting that things are in place that early issues which were fairly forward looking are being closed out. It feels like an actual release could be coming up if I can clean up the API for using bosatsu from scala/java.
=> Add Dict syntax handling

core/src/main/scala/org/bykn/bosatsu/DefStatement.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
close #17 
This allows newlines inside def and constructors. This makes longer lists of args more readable.
=> allow newlines inside constructor and defs

core/src/main/scala/org/bykn/bosatsu/Identifier.scala, core/src/main/scala/org/bykn/bosatsu/Program.scala, core/src/main/scala/org/bykn/bosatsu/StringUtil.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
close #70 
This is pretty easy after the #192 cleanup.
The JSON test shows the motivation: make objects with keys which are keywords in bosatsu.
=> Add backtick escaping to allow any string as a binding

core/src/main/scala/org/bykn/bosatsu/Test.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
The idea here is to:
1. exercise the built in testing code in predef more.
2. write more tests fully in bosatsu vs having to encode the results as Value.
3. make it easier to have many assertions in a single test.
4. increase test coverage since we weren't exercising the Evaluation test support in scalatest tests.
=> Add support to run bosatsu tests inside scala tests

core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/Regressions.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
I added a requirement (which I thought was there) that metas never escape. It's not cool to have that requirement, but it does show that there are a few places with this bug currently.
this was discovered in #196 
I guess we are missing a call to quantify/zonk...
However, if that were the case, those shoudn't cause anything to not typecheck. I think this is also related to recursive methods. I think all the current examples of failures are recursive methods.
=> Issue with metavariables not fully inferred

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/Expr.scala, core/src/main/scala/org/bykn/bosatsu/Identifier.scala, core/src/main/scala/org/bykn/bosatsu/Operators.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/OperatorTest.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
Implement the proposal from #12 
cc @snoble
=> Add basic operator support

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/DefStatement.scala, core/src/main/scala/org/bykn/bosatsu/Expr.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/Program.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala
close #211 
which seems like we need to have to be consistent between lambdas and defs, and to emphasize the importance of patterns in bosatsu.
It seems like this *should* close #212 but for a reason I don't yet understand, I can't yet parse `\x: Int -> x` we need to have `\(x: Int) -> x` despite bare type annotations working for defs. I'll debug that in a separate PR.
cc @snoble
=> Support patterns in def args

dependencies.yaml, test_workspace/BUILD, test_workspace/bazel_deps_api.bosatsu, test_workspace/dicttools.bosatsu, test_workspace/gen_deps.bosatsu, update_deps.sh
close #205 
related to #21 
This is a start of using bosatsu to generate the depedencies.yaml file in this repo. It is a good dog-fooding exercise as I've already hit two issues:
0. you can't get the ordering out of an existing map. This makes it more painful to make new maps.
1. no merge function on maps and hard to write due to the above.
2. lack of both type-aliases the default rules for Json conversion is pretty painful. It means you often have to work with big types. I think type aliases probably make sense, or the approach of making 1 item structs not use object wrapping...
3. new-lines between keys and values in literal dicts don't work, which is annoying.
I'm a bit concerned the single way of constructing Json from types will turn out to be very restrictive and require two sets of …
=> use bosatsu to generate dependencies.yaml

core/src/main/scala/org/bykn/bosatsu/Padding.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
previously, we fail to parse any statement if any item in the linked list that forms the top statement fails.
This is obviously terrible.
This PR fixes it taking the approach suggested in:
https://github.com/johnynek/bosatsu/issues/90#issuecomment-480527578
I need to do the same with Declaration.
Note the test I added originally failed at index 0 which is to say it never parsed anything. Now it fails at the statement that can't be parsed. Ideally we would point at the dictionary, but this is an improvement.
=> Improve parsing of statements

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala
We had implemented type substitution twice, since I forgot it was hiding inside Infer. This moves the infer version into Type and adjusts some type parameters to use it.
Infer needs to be able to substitute skolem vars, not just bound vars, so the type was broadened.
=> Remove duplication of type substitution

core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
part of #225 
This seems to solve the open problems. This approach exposes an issue in this approach: if we have unknown types in an apply, we should really introduce variables to track what final variance is substituted in. This does not do that, and instead falls back on a worse case of invariance.
=> Use variance in skolemization and substitution

test_workspace/BUILD, test_workspace/Queue.bosatsu, test_workspace/TreeList.bosatsu
This adds two implementations of potentially useful libraries as bosatsu examples, and immutable Queue and TreeList both originally described by Chris Okasaki.
This is the first "library code" I've ever actually written in bosatsu, and I really liked it. I think there are still patterns to be learned in the language, but I'm pretty happy living without typeclasses actually and just manually passing functions around. In this example I wrote `eq_Queue` and `eq_TreeList` which each themselves take functions to check equality on items, and returns a function to check equality on the data structure. This is exactly writing the `Eq` instances by hand, but it really doesn't seem very painful in this case to do so.
I am exploring a kind of strange style lately: actively using shadowing in order …
=> Add two data structure examples: Queue, TreeList

core/src/main/scala/org/bykn/bosatsu/CommentStatement.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala
minor code cleanup.
I want to get back to the style of one top-level name per scala file. I've been slack in some cases, and that makes the code harder to navigate.
=> Move CommentStatement to a separate file

core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/Program.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/main/scala/org/bykn/bosatsu/TypeRef.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
close #83 
This is pretty easy it turns out, but since we have no errors allowed going from syntax into types, it means we have coerce anything into something meaningful. Two error conditions that are ignored currently:
1. duplicating type parameters shouldn't be allowed (similarly with value parameters)
2. I think we want type parameters to be a superset of the free type parameters in the args.
I think the right way to deal with these two cases are lints that run on the source code that give warnings or errors (depending on the package's source defined strictness, see #241 ), but we want to give the user as much feedback as possible, so it is good to be able to run the typechecker on the sanest interpretation of the input.
What do you think @snoble ?
=> Allow struct and enum to have explicit type arguments

WORKSPACE, build.sbt, cli/src/main/protobuf/bosatsu/BUILD, cli/src/main/protobuf/bosatsu/TypedAst.proto, cli/src/main/scala/org/bykn/bosatsu/BUILD, cli/src/main/scala/org/bykn/bosatsu/TypedExprToProto.scala, cli/src/test/scala/org/bykn/bosatsu/TestProtoType.scala, project/Dependencies.scala, project/plugins.sbt
This adds a protobuf representation of `rankn.Type`. This is kind of a bottom up approach. The top is Package.Interface and Package.Typed that we want to serialize.
I have bad internet currently and I can't download the dependencies to get the bazel proto build working locally. I will need to do that before merging, but I may press on in a series of PRs that I fix up after the fact.
=> Add conversion to and from protobuf for Type

bench/src/main/scala/org/bykn/bosatsu/TestBench.scala, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Identifier.scala, core/src/main/scala/org/bykn/bosatsu/Predef.scala
Gets almost 2x better. Not the 100x we got in #247 but still an improvement.
1. adds a benchmark of the slowest Euler problem and used that with jstack to look for cheap wins
2. the "optimization" of cleaning the Env in closures was hurting, not helping, so that was removed.
3. interning Identifiers and caching the hashCode was somewhat helpful
4. a few changes in memoization helped.
before:
```
[info] Benchmark          Mode  Cnt      Score     Error  Units   
[info] TestBench.bench0  thrpt    5  12098.270 ± 739.487  ops/s   
[info] TestBench.bench1  thrpt    5   8311.776 ± 400.025  ops/s   
[info] TestBench.bench2  thrpt    5      1.719 ±   0.115  ops/s~
```
after:
```
[info] Benchmark          Mode  Cnt      Score     Error  Units                             
[info] TestBench.bench0 …
```
=> More Evaluation optimizations

cli/src/main/protobuf/bosatsu/TypedAst.proto, cli/src/main/scala/org/bykn/bosatsu/BUILD, cli/src/main/scala/org/bykn/bosatsu/Main.scala, cli/src/main/scala/org/bykn/bosatsu/TypedExprToProto.scala, cli/src/test/scala/org/bykn/bosatsu/TestProtoType.scala, core/src/main/scala/org/bykn/bosatsu/Codegen.scala, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/ExportedName.scala, core/src/main/scala/org/bykn/bosatsu/Identifier.scala, core/src/main/scala/org/bykn/bosatsu/Normalization.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/rankn/NTypeGen.scala, core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala, tools/bosatsu.bzl
part of #54 
This adds proto serialization of interfaces, but does not yet use them.
The idea is to allow the CLI to depend on proto interfaces and avoid having to transitively recompile code in order to use dependencies. We should also emit proto interfaces when we compile. Lastly, we need to make the bazel rules aware of these so it can plumb them through correctly. That will be in follow up PRs.
=> Add Proto version of package interfaces

bench/src/main/scala/org/bykn/bosatsu/TestBench.scala, cli/src/main/scala/org/bykn/bosatsu/Main.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/test/scala/org/bykn/bosatsu/CodegenTest.scala, core/src/test/scala/org/bykn/bosatsu/PackageTest.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala, tools/bosatsu.bzl
This changes the type-check command to emit protobuf interface files and consume those from dependencies rather than recompiling the full source.
This is only useful to improve the speed of `bosatsu_library` it does not help `bosatsu_test` because that has to evaluate the code, and we have not yet implemented a full serialized typechecked package.
part of #54 
The format of the protobuf still probably needs work: the assumption that types are small seems false so we probably want to build a full type table and reference those as integers so we don't declare them over and over, and also probably the same for package names.
one issue is that the version of protobuf we are pulling in gives this warning:
```
WARNING: An illegal reflective access operation has occurred …
```
=> Use interface files in bosatsu_library

core/src/main/scala/org/bykn/bosatsu/NameKind.scala, core/src/main/scala/org/bykn/bosatsu/Normalization.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/Program.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
To serialize compiled packages, we don't want to serialize the source ADTs (I don't think). But currently, evaluation actually reaches all the way back to the source to get the list of external defs. If we need them, we should explicitly put them on Program. That's what this PR does.
=> Put external defs in Program

cli/src/main/protobuf/bosatsu/TypedAst.proto, cli/src/main/scala/org/bykn/bosatsu/TypedExprToProto.scala
This adds the protos to serialize `Pattern`, `TypedExpr`, and `Package.Typed`.
Some small changes to Interface: put all the tables first, rename the strings table to `strings` instead of `constants`.
=> Add protos for Package.Typed

cli/src/main/protobuf/bosatsu/TypedAst.proto, cli/src/main/scala/org/bykn/bosatsu/TypedExprToProto.scala, cli/src/test/scala/org/bykn/bosatsu/TestProtoType.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala
part of #54 
This adds conversion of TypedExpr to proto. Along the way, it also makes TypeExpr covariant.
=> Add serialization of TypedExpr to proto

core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
related to #267 and #269 
Before this PR, `Rho` was a type alias for `Type` as in the paper. Scala's subtyping allows us to define it as a real type, and let the compiler check some of the invariants we claim. Doing this didn't seem to uncover any new bugs, but seems valuable for safety.
There are two other invariants not checked:
1. Type.Tau: no ForAll anywhere. For instance `(forall a. a) -> Foo` is a Rho type, but not a Tau type.
2. weak-prenex form: this means we have moved all the ForAlls up as far as possible using covariance.
While doing this, I added a variant of the tests in #269. I think at least part of our issue is around pattern matches. Currently, we would do a subsCheck eventually on a meta variable, against an annotated `forall` type, and that will always fail if the type. …
=> Make Type.Rho a real type, not an alias

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
this improves compilations of `pattern = foo` bindings inside expressions. The goal is to minimize the use of Match, which is more expensive in that we have to check those for totality. This instead uses `Expr.Annotation` and `Expr.Let` in two cases, allowing more patterns to avoid a single arm match.
=> Improve Pattern compilation in expressions

core/src/main/scala/org/bykn/bosatsu/graph/Toposort.scala, core/src/main/scala/org/bykn/bosatsu/graph/Tree.scala, core/src/test/scala/org/bykn/bosatsu/graph/ToposortTest.scala, core/src/test/scala/org/bykn/bosatsu/graph/TreeTest.scala
We need this to deserialize interfaces and compiled code that depends on each other, without duplicating data inside the packages.
=> Add Topological sort function

core/src/main/scala/org/bykn/bosatsu/Normalization.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/NormalizationTest.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala, test_workspace/euler1.bosatsu
when starting to use the proto output I discovered new lurking bugs. The proto cannot serialize metavars or skolems, which should never appear in fully compiled code. Unfortunately that wasn't the case.
The top-level types for lets in the `TypedExpr` were correct, but inside there could still be meta-vars or skolems that shouldn't have been there. The full typing is something the paper is a bit short on and I made some mistakes implementing it.
I still have some questions, but it seems at least the bugs that were present are gone.
After this is merged, I should be able to send the PR which enables incremental compilation using the protobuf outputs.
=> Fix bugs uncovered with a stricter checks

core/src/main/scala/org/bykn/bosatsu/Normalization.scala, core/src/test/scala/org/bykn/bosatsu/NormalizationTest.scala
I came across two bugs in normalization when I tried to use it for caching. In one case it would crash when trying to normalize some code (see `Substitution/Lambda`). In the other case `\x,y -> x(y)` would become `Lambda(LambdaVar(1))` (which would suggest being bound to an outer lambda which doesn't exist)
=> Normalization bugs

core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
This should increase code coverage because we had some uncovered branches, due to them statically not being reachable, as we see here with slightly tighter types.
It could be we should be using the infer branch of this code, but I don't see why we should.
=> Remove some unreachable Infer code

test_workspace/BUILD, test_workspace/Nothing.bosatsu
In a non-total language, we would need the ability to make enums with no variants.
In a total language, `forall a. (a -> a) -> a` is uninhabited, so we can use a struct containing one as a synonym for Nothing. If we ever had one, we could produce any value.
=> Add Bosatsu/Nothing, showing how to make a Nothing or Void type

build.sbt
This is an attempt to make the CI run better in scalajs. I'd like to reduce the number of trials we run in scalajs, but naively following the approach I thought would work in #299 didn't work.
I don't really know where sbt decides to magically look for files, and adding the platform files to `core/js/...` didn't seem to get picked up, but maybe I made a mistake.
=> Copy scalajs options from paiges

core/src/main/scala/org/bykn/bosatsu/Expr.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala
Removes a few TODOs around symbol allocation by reusing buildPatternLambda and by allocating names that can't possibly collide with internal names.
=> Allocate Bindable names by explicitly avoiding used names

cli/src/main/scala/org/bykn/bosatsu/TypedExprToProto.scala, core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Normalization.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala
Previously, we have been using types like `Option[Bindable]` to mean, either a tuple or named struct, or `Either[Option[Bindable, Pattern[N, T]]` to mean an element of a list pattern that can either be an unnamed splice `*_`, a named splice `*foo` or a regular pattern.
This is clearly an insane style. Just make new types so you can see what is going on.
As I want to add more to pattern matching for #289 and #301 now is a good time to improve this code.
=> Add better types in Pattern

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, docs/language_guide.md
This PR adds the parsing of creating structs and enums using record syntax.
The variant in #289 I went with was the dict-like syntax:
```
struct Foo(bar: Int)
f = Foo { bar: 3 }
struct Person(name: String, age: Int)
name = "Alice"
age = 37
p = Person { name, age }
```
I didn't implement pattern matching yet, but that would work like:
```
Person { name: nm, ... } = p
Person { name, ... } = p
```
The analogy was suggested by @avibryant : you can make values with tuple-like or dict-like syntax (but not a hybrid of the two).
Lastly, I've decided to make one minor change: pattern matches on structs/enums must cover all the fields or explicitly add `...` to say you don't care about the rest of the fields. To preserve the duality between matching and creation, I may remove automatic currying of …
=> Add struct/enum record syntax

core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
close #306 
We don't do anything different yet, but when we update the code to handle record syntax, we should add the checking then (see #308).
=> Add ellipsis to ADT parsing

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/main/scala/org/bykn/bosatsu/TypeRefConverter.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala, core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala, core/src/test/scala/org/bykn/bosatsu/TypeRefTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
close #308 
Translate record syntax, so we don't need to change anything about typechecking or evaluation.
I did hit a new bug here filed at #311
=> Rewrite records into tuple-like syntax

core/src/main/resources/bosatsu/predef.bosatsu, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/OperatorTest.scala, test_workspace/ApplicativeTraverse.bosatsu, test_workspace/List.bosatsu, test_workspace/Queue.bosatsu, test_workspace/TreeList.bosatsu, test_workspace/euler6.bosatsu, test_workspace/euler7.bosatsu, test_workspace/recordset.bosatsu, test_workspace/test_example.bosatsu
Originally, this is how Test worked, but when we temporarily removed when recursive types (#102) were removed before we added checks for covariant recursion (#158).
I should have done this when I added list back in #159.
=> Use covariant recursion in the built in Test type

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/rankn/TypeEnv.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
fix #328 
This does to by explicitly evaluating the file in the order we type-check it, with the correct environment at each point.
=> Fix issue 328, evaluation/typechecking inconsistency

core/src/main/scala/org/bykn/bosatsu/BindingStatement.scala, core/src/main/scala/org/bykn/bosatsu/Expr.scala, core/src/main/scala/org/bykn/bosatsu/ListLang.scala, core/src/main/scala/org/bykn/bosatsu/Operators.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
Ideally, the parser can point to as close as possible to where a parse fails. Unfortunately, we are using a fair amount of backtracking currently in the parser, which makes it both slower and also prone to print unhelpful error messages.
By reducing backtracking, which can be done in fastparse with more cuts, we can print better locations for parser errors.
In some cases, we need to restructure the parsers to avoid using backtracking. For instance, we have two mechanisms to parse binds, rather than parsing a prefix, and then upon seeing `=` always move to parsing a bind. Similarly, trailing `if` is an operator if it has an `else` but it is also a filtering operation in a for comprehension. Ideally we should have a parser that knows that trailing is isn't allowed unless nested in a parens, …
=> Add cuts for more precise parser errors

test_workspace/BUILD, test_workspace/BuildExample.bosatsu, test_workspace/BuildLibrary.bosatsu
This adds a compile-only example of using Bosatsu in a bazel-like use case. First we implement a toy API that is real enough (has a Build type constructor and it composes in an applicative fashion), then we use the API to write two build targets.
It is clearly advanced functional programming to encode the Build library, but using it seems like it could be done without a huge depth of knowledge. I don't think this is a real problem, since writing libraries is generally harder writing application code since libraries are generally encoding some abstraction, but the encoding of the library is probably not a great sales pitch so far.
On the other hand, it is quite interesting we can encode all of this in a total functional language without any problem now.
cc @snoble
=> Add an example of bazel-like use case

.travis.yml, core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/Padding.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/test/scala/org/bykn/bosatsu/DefRecursionCheckTest.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/FreeVarTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
This refactors a design I've not been happy with: Statement is an ADT with a built in linked list. This creates parsing complications, and also weird ambiguities in that we can never deal with a single statement (but we kind of pretend to by dealing with the head).
This fixes this.
=> Remove the built-in List structure of Statement

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
This does not, I believe, improve performance (much?). It just improves the way the code is factored.
There is an ambiguity in the syntax which requires some backtracking it seems around bindings.
```
pattern = decl
```
so, we don't know until we see `=` if the left should parse as a pattern. So, if we parse it as a declaration, we would need to convert it to a pattern, or if we parse it as a pattern, we would need to convert it to a declaration if the `=` is not present.
Relates to #344
=> Improve Declaration parsing code

core/src/main/scala/org/bykn/bosatsu/BindingStatement.scala, core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/Operators.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
close #357
This introduces `Declaration.NonBinding` which prevents us from writing code like:
```
x = y = z
f(y)
f(x)
```
which would have confusingly been the same as:
```
f(f(z))
```
=> Improve Record Declaration Parsing

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
close #265 
This turned out to be much more complex than I thought.
The key issue is that this creates a lot of ambiguity. consider `if x:` what comes next? if we expect `x: type` it fails to parse, which when done wrong makes us fall back to parsing `if` as a variable.
or consider in `match x:` what should come next? Lastly, dictionaries use the colon as well.
My solution is to make type annotation unusable in those locations without a `(x: type)` nesting. I think this is a fine solution
I think this allows us to use type annotations all the places we expect.
cc @snoble please reopen #265 if you see this in the future.
=> Fix 265, parse type annotations

core/src/main/scala/org/bykn/bosatsu/Expr.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
this was an attempt to fix #321 but I couldn't yet get there.
My idea was to not fully skolemize all free variables, but instead look for the lambda patterns and only skolemize the lambdas. This makes it much more complex to see when variables escape. I wonder if this is a misfeature...
Alternatives:
1. only do this for top level declarations.
2. require type annotations like `def foo[a](x: a)` and only quantify over the declared variables.
It seems like we should be able to infer which are free, but more inference is also a double edged sword: it makes more programs type-check that the user might not intend. I'm not sure where the balance is in this case.
skolemizing all free variables for each top-level let is certainly simpler.
=> Refactor skolemize freevar

.travis.yml, cli/src/main/scala/org/bykn/bosatsu/Main.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
I am working towards having a javascript API. The approach is to expose functions that match the CLI.
This PR takes all the IO work in the main method and abstracts it. Then we can share parsing a `List[String]` into a command to run.
This also helps us improve test coverage (once we use this) since we can exercise the same paths.
I will change the TestUtils to call MainModule to run tests, evaluate, and run bosatsu tests.
=> Add MainModule to generalize the CLI api

elmui/build.sh
the setup for the deploy key was broken, but ssh rather than reporting a bad key, just waits for a passphrase. IMO, using `ssh -i` on an identity it can't parse should be fatal.
=> Try again on the deploy front

bench/src/main/scala/org/bykn/bosatsu/TestBench.scala, core/src/main/scala/org/bykn/bosatsu/LocationMap.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/main/scala/org/bykn/bosatsu/Predef.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala, elmui/Makefile, elmui/elm.json, elmui/index.html, elmui/src/Main.elm, jsapi/src/main/scala/org/bykn/bosatsu/jsapi/JsApi.scala
This moves parsing the result from the bosatsu js api into elm. This paves the way for a more structured response from bosatsu.
=> Move interop code from js to elm

bench/src/main/scala/org/bykn/bosatsu/TestBench.scala, cli/src/main/scala/org/bykn/bosatsu/Main.scala, cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/MemoryMain.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageName.scala, core/src/main/scala/org/bykn/bosatsu/Predef.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/PackageTest.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala, elmui/index.html, jsapi/src/main/scala/org/bykn/bosatsu/jsapi/JsApi.scala
closes #10 
This allows the option of passing a list of package_roots, which if there is no explicit `package` in a file, we check if the given path is in the root in the order they are given.
This allows us to have implicit package names in the web UI, but could also be very useful in applications like bazel where you don't want to have to declare a redundant package name.
In Path based examples, we pass the relative path to `toLowerCase.capitalize` in an attempt to make it a valid package name.
=> Support implicit package names

core/src/main/scala/org/bykn/bosatsu/MainModule.scala, jsapi/src/main/scala/org/bykn/bosatsu/jsapi/JsApi.scala
Does two things:
1. report the type of the item we can't convert to JS in terms of bosatsu syntax, not a giant internal AST.
2. use `err.getMessage` not `err.toString` which also prints the type of the error.
=> Improve error message on javascript tool

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/Predef.scala, core/src/main/scala/org/bykn/bosatsu/Value.scala, core/src/main/scala/org/bykn/bosatsu/rankn/DefinedType.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/ValueTest.scala
close #331 
This optimizes evaluation for a few cases:
1. unit like types can do less work
2. enums that are like ints are memoized for fewer allocations
3. when we have a struct match that doesn't do any binding (`Foo(_, _)`) we simpilfy things
4. we optimize the representation of Nat-like types so they are stored by a BigInteger, not a linear-sized linked list
5. new-types don't add a layer of wrapping.
cc @snoble
=> Improve Evaluation

bench/src/main/scala/org/bykn/bosatsu/TestBench.scala, bosatsuj, build_native.sh, cli/src/main/scala/org/bykn/bosatsu/Main.scala, cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/LocationMap.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/MemoryMain.scala, core/src/main/scala/org/bykn/bosatsu/Predef.scala, core/src/main/scala/org/bykn/bosatsu/Test.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala, test_workspace/Bar.bosatsu, test_workspace/Foo.bosatsu
This was plane code done to improve the usability of the CLI:
1. compiling bosatsu with native-image makes the CLI much nicer to use, so it would be nice not to have to use bazel for basic things, without compromising the correctness of the bazel operation.
2. for a python-like experience, it is nice to run a file, and have a `--search` mode for to automatically look for files based on package name. `--search` should probably be the default when you give a package_root, so I think that should be changed to `--no-search` to disable.
3. colorization flag should work for `test`.
4. test should find the last test value, not the last value. This is more general, so shouldn't break anything. By doing this you can do both tests and json for a single file.
5. `write-json` should have an optional …
=> Improve the usability of the CLI

test_workspace/List.bosatsu
Adds some standard list functions to exercise the language and explore patterns.
I like the approach of using:
```
def zip_tests:
t1 = match ...
```
to do three things:
1. use a def with no args to set up a limited scope.
2. inside make a TestSuite to group the assertions
3. use match to get easier writing of tests.
=> Add some List functions

core/src/main/scala/org/bykn/bosatsu/MainModule.scala
when I was adding the multiple ways to use the CLI, things kind of broke IMO in that if you give a bit list of sources to test, and then tell it an explicit file to test, it will test everything and complain that some files don't have tests.
If you explicitly give a set of tests, only test those.
=> Only test the explicit tests if explicit tests are given

cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala, core/src/main/resources/bosatsu/predef.bosatsu, test_workspace/BUILD, test_workspace/List.bosatsu
This stumped me at first, but the solution is quite instructive and I think rather general: find some companion structure that proves the computation terminates and carry that through with you in the recursion. This can be removed from the API by computing the companion structure internally.
=> Add quicksort implementation to List

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/ListLang.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/test/scala/org/bykn/bosatsu/OperatorTest.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
improve #90 
related to #344
The motivator here was finding that we couldn't use operators in `if` clauses in list comprehensions, but I by adding more cuts I could improve the localization of errors in a few cases.
=> Improve localization of parser errors

bench/src/main/scala/org/bykn/bosatsu/TestBench.scala, core/.js/src/main/scala/org/bykn/bosatsu/Par.scala, core/.jvm/src/main/scala/org/bykn/bosatsu/Par.scala, core/src/main/scala/org/bykn/bosatsu/IorMethods.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/Predef.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/PackageTest.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
We were generally using Validated to model failure and being careful about using andThen. But there was also a case where we had a side optional error because we wanted to continue after a failure.
This moves to using Ior in those cases so we can be more explicit.
The risk here now is that the default traverse/sequence/mapN won't accumulate like we like, so we need to use parTraverse, parSequence, parMapN, but I think I have done that correctly.
This cleanup was motivated by wanting to put more lints in but have more confidence that we are not breaking things.
=> Use Ior more to better model partial failure

core/src/main/resources/bosatsu/predef.bosatsu, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/Region.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/UnusedLetCheck.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/NormalizationTest.scala, core/src/test/scala/org/bykn/bosatsu/PackageTest.scala, core/src/test/scala/org/bykn/bosatsu/PatternTest.scala, core/src/test/scala/org/bykn/bosatsu/TypedExprTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala, test_workspace/ApplicativeTraverse.bosatsu, test_workspace/BinNat.bosatsu, test_workspace/TreeList.bosatsu, test_workspace/euler2.bosatsu, test_workspace/euler3.bosatsu, test_workspace/euler4.bosatsu, test_workspace/euler5.bosatsu, test_workspace/recordset.bosatsu
close #419 
This makes unused bindings an error. This is purely a change to make it easier to write correct code.
We cannot remove the unused let normalization because other changes in the graph can make a let unused. This is only a naive check that a variable is literally never used. It may still be removable by optimizations and normalizations.
Our goal here is simply to error on cases where trivial syntactic analysis we should something is unused.
=> Make unused bindings an error

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, test_workspace/euler7.bosatsu
I accidentally had trailing whitespace in a file and got a parse error, which was not great. Trailing whitespace isn't awesome, but it shouldn't cause a parse failure.
Also, this allows us to use `=` to make a block simliar to `:` so you can do:
```
x = Foo(some, really, long, call)
x = 
Foo(
some,
really,
long,
call,
)
```
as long as there is indentation after the `=` on the next line.
=> Allow newline after =, allow any file trailing whitespace

cli/src/main/protobuf/bosatsu/TypedAst.proto, cli/src/main/scala/org/bykn/bosatsu/PathModule.scala, cli/src/main/scala/org/bykn/bosatsu/TypedExprToProto.scala, core/src/main/resources/bosatsu/predef.bosatsu, core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/ListLang.scala, core/src/main/scala/org/bykn/bosatsu/Lit.scala, core/src/main/scala/org/bykn/bosatsu/Normalization.scala, core/src/main/scala/org/bykn/bosatsu/OptIndent.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/Padding.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/Predef.scala, core/src/main/scala/org/bykn/bosatsu/SimpleStringPattern.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/main/scala/org/bykn/bosatsu/StringUtil.scala, core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, core/src/test/scala/org/bykn/bosatsu/SimpleStringPatternTest.scala, test_workspace/PatternExamples.bosatsu, test_workspace/StrConcatExample.bosatsu
closes #426 
Since pattern and declaration parsing are related, it is not easy to add part of this, so this PR adds everything, expressions for interpolation as well as pattern matching for pattern strings.
Along the way, I improved my understanding of the set algebra of sequences so I think we can leverage this to check totality when we have multiple variable patterns in lists as well, which is probably complex to reason about, but at least doesn't create a difference with string patterns.
=> Support for string interpolation and matching

core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, test_workspace/TreeList.bosatsu
close #433 
also closes a TODO to catch some bad patterns.
Previously, we were repeatedly validating patterns as we were computing the intersections and differences. This make a change to do one pass to validate and check everything, then compute the missing and unreachable patterns after that. This should be both more efficient as well as catching errors we were not catching before.
=> Improve pattern checking

core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala
I found a better formula for list intersection, and i think difference.
I don't have a totally rigorous proof, but the laws seem to pass when using this formula for intersections. This means intersections on lists do not depend on the invariant that there is at most one repeated pattern. I'd really like to remove assuming that to compute totality of list patterns since this creates an irregularity between strings and lists.
Unfortunately, when I tried to use the new formula (based on similar approaches) in list difference, several tests failed. In the worst case, the code may be subtly (since tests pass) broken for string patterns as well.
It may possibly be related to the fact that the string differences are not exact and perhaps not precise enough. When we do `x - y` we return a …
=> Improve list intersection based on recent work

.travis.yml, cli/src/main/scala/org/bykn/bosatsu/PathModule.scala, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/TypeName.scala, core/src/main/scala/org/bykn/bosatsu/Unique.scala, core/src/main/scala/org/bykn/bosatsu/ValueToDoc.scala, core/src/main/scala/org/bykn/bosatsu/ValueToJson.scala, core/src/test/scala/org/bykn/bosatsu/JsonTest.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala, core/src/test/scala/org/bykn/bosatsu/ValueToDocTest.scala, elmui/Makefile, elmui/index.html, elmui/src/Main.elm, jsapi/src/main/scala/org/bykn/bosatsu/jsapi/JsApi.scala
close #431 
This makes eval much nicer to work with, and I adjusted the js API to use it as well, rather than json output (it could be an option we control in the UI).
The testing isn't great, but I did a lot of spot checks at the CLI. I think there may be some evolution, but I liked where we got. For instance:
```
./bosatsuj eval --search --package_root test_workspace/ --input_dir test_workspace/ --main GenDeps
gives:
Config {
options: Options {
buildHeader: ['load("@io_bazel_rules_scala//scala:scala_import.bzl", "scala_import")'],
languages: ['java', 'scala:2.11.11'],
resolvers: [Resolver {
id: 'mavencentral',
type: 'default',
url: 'https://repo.maven.apache.org/maven2/'
}],
transitivity: 'runtime_deps',
resolverType: 'coursier',
versionConflictPolicy: 'highest'
},
dependencies: …
```
=> Add support for converting values to Doc

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
related to #396 
It occurred to me if we had the `\if Foo(x) -> fn(x)` syntax for making partial functions, then we could generate `Option` values with:
```
x.(\if Foo(y) -> fn(y)): Option[a]
```
maybe the syntax is too dense, but `|>` type compositions which do `x |> f = f(x)` which is what we have `x.f` doing, but we only allow names for `f` not any other form. Since `.(f)` is unambiguous to parse, we could allow more which can be useful in some cases...
=> Allow a new form of apply

core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
close #449 for now. At least print the hint that a function failing to unify with a non-function is usually an arity mismatch.
=> Improve error message on arity mismatch

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/Value.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/TypedExprTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala
close #434 
This should allow us to remove using Eval internally, which could be a huge performance improvement.
=> Optimize tail recursion in Evaluation

bench/src/main/scala/org/bykn/bosatsu/TestBench.scala, cli/src/main/scala/org/bykn/bosatsu/PathModule.scala, cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Externals.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/Predef.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/Value.scala, core/src/main/scala/org/bykn/bosatsu/ValueToJson.scala, core/src/test/scala/org/bykn/bosatsu/GenValue.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
Since we have solved #434 we don't need Eval to make any loop stack safe. More over, by forcing us to use that more, we work any bugs out of that system before we make a backend that would almost certainly want to not put trampolines everywhere.
There is still some laziness here in the environment since setting up a recursive value is using it. That could still probably be removed or reduced for more performance improvements.
benchmarks show 80% faster on the most time consuming benchmark.
```
[info] Benchmark          Mode  Cnt      Score      Error  Units    
[info] TestBench.bench0  thrpt    3  13190.738 ±  463.814  ops/s    
[info] TestBench.bench1  thrpt    3  10599.481 ± 5759.104  ops/s    
[info] TestBench.bench2  thrpt    3      2.706 ±    0.574  ops/s    
[info] Benchmark …
```
=> Make FnValue Value to Value not Eval to Eval

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
close #274 
@snoble 
I decided to keep it simple: copy python and always use the `\` to continue. So you can write:
```
x         \
.foo    \
.bar(y) \
```
to do method chaining.
The `\` means a few things:
1. discourages long chains slightly.
2. there is only one way (vs. allowing but also inferring, but inferring doesn't work in a repl session)
3. matches python.
Sorry it took so long. It was really only a few lines of code.
=> Add support for backlash continuation of apply chains

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, test_workspace/AvlTree.bosatsu, test_workspace/Bar.bosatsu, test_workspace/List.bosatsu, test_workspace/Nat.bosatsu, test_workspace/PatternExamples.bosatsu, test_workspace/Queue.bosatsu, test_workspace/euler4.bosatsu
close #396 
take a look @avibryant @snoble if you have time.
I like this syntax and think it is pretty useful as you can see in the examples I changed.
The fact that rust recently added a macro for this seals the deal for me since I didn't know about that when I was thinking about this. The fact that it was independently considered by the rust folks seems like good evidence.
=> implement matches syntax

core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/NormalizationTest.scala, core/src/test/scala/org/bykn/bosatsu/TypedExprTest.scala
Since Lists are first class types, we have an issue where we have both the literal list an named struct form of a pattern.
This PR handles that case.
=> Handle both struct and list form of list patterns

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala
We were needlessly recursing an extra time on all rhs of let bindings, and twice for the case of recursive functions.
This isn't incorrect, but it is wasteful.
=> Remove wasteful calls in evaluation

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/test/scala/org/bykn/bosatsu/DeclarationTest.scala
close #493 
The main bug here was that the short form of records `Foo { x }` meaning `Foo { x: x }` was seen in substitution, but overlooked in freeVars and allVars, so one of the scalacheck tests caught that. *yay*.
freeVars and allVars had copied code that was ignoring the filter condition which I noticed while looking for more bugs.
I added tests that triggered all the bugs I saw, then made sure they were green. I also turned up the number of trials to 5000 and made sure it passed locally before turning back down to 200 (since these tests are slow, since, I believe the declarations are sometimes getting really deep).
cc @snoble thanks for reporting this bug. With your report, it was easy to fix the error.
=> fix bugs in freeVars, allVars and substitute in Declaration

core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala, core/src/main/scala/org/bykn/bosatsu/pattern/Matcher.scala, core/src/main/scala/org/bykn/bosatsu/pattern/SeqPart.scala, core/src/main/scala/org/bykn/bosatsu/pattern/SeqPattern.scala, core/src/main/scala/org/bykn/bosatsu/pattern/SetOps.scala, core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala, core/src/test/scala/org/bykn/bosatsu/pattern/SeqPatternTest.scala, core/src/test/scala/org/bykn/bosatsu/pattern/SetOpsLaws.scala, core/src/test/scala/org/bykn/bosatsu/pattern/StringSeqPatternSetLaws.scala
This is an attempt to fix #491 #486 #480 #475.
The problem is that difference is an upper bound for SeqPattern with wildcards at both ends.
I think this is not a soundness problem because it rejects some patterns that are total, but it can't see that they are. It would be nice to minimize those however.
This code fixes a couple of real bugs, comments out one law that is only approximately true, and adds a heuristic for improving the checks for missing branches (which can be pessimistic, but should never report that a match is total when it isn't).
=> Improve SeqPattern testing

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/ValueToDoc.scala, core/src/main/scala/org/bykn/bosatsu/ValueToJson.scala, core/src/main/scala/org/bykn/bosatsu/rankn/ConstructorFn.scala, core/src/main/scala/org/bykn/bosatsu/rankn/DataRepr.scala, core/src/main/scala/org/bykn/bosatsu/rankn/DefinedType.scala, core/src/test/scala/org/bykn/bosatsu/JsonTest.scala, core/src/test/scala/org/bykn/bosatsu/ValueToDocTest.scala
this makes an ADT where we previously had some access functions on DefinedType.
The goal here is to use the same ADTs in the matchless IR #478 and then we should be able to swap out Evaluation
to be an interpreter for the Matchless IR which removes duplication.
=> Add DataRepr to improve factoring of code

core/src/main/scala/org/bykn/bosatsu/pattern/SeqPattern.scala, core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala, core/src/test/scala/org/bykn/bosatsu/pattern/SeqPatternTest.scala, core/src/test/scala/org/bykn/bosatsu/pattern/SetOpsLaws.scala
I was being a bit dense about a key formula `A - (B | C)` which @non reminded me is `(A - B) n (A - C)`. By using this, then a slight upper bound, the formula in the worst case for difference gets a lot simpler.
I also added property checks for the logic formulas I'm using. They should be theorems from the axioms of set theory, but just to make sure I don't make future mistakes, I'll add tests (I guess if I were really cool I'd include coq proofs or something).
=> Improve SeqPattern.difference, test boolean formulas

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Identifier.scala, core/src/main/scala/org/bykn/bosatsu/Lit.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/Matchless.scala, core/src/main/scala/org/bykn/bosatsu/MatchlessToValue.scala, core/src/main/scala/org/bykn/bosatsu/Value.scala, core/src/main/scala/org/bykn/bosatsu/graph/Memoize.scala, core/src/main/scala/org/bykn/bosatsu/rankn/DataRepr.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Ref.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/MatchlessTests.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
The motivation of this PR is to: 
1. exercise Matchless in tests and the design
2. reduce duplication that would otherwise exist with the current interpreter/evaluation
The goal of Matchless is an AST that can be a basis for code generation since it doesn't rely on anything very fancy (still assumes certain things like allocation and delegates ADTs and lambdas to the underlying system).
It was pretty complex to get the tests passing due to the mutability that this code uses as it is evaluating the if/else that the matches compile into. As we pass parts of the match, we can set variables that were previously unset. Doing this in the wrong order gives very hard to debug issues.
=> Replace Evaluation logic with Matchless

core/src/main/scala/org/bykn/bosatsu/MatchlessToValue.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/Value.scala
A value is static if it is fully known at compile time.
An example of a value that is:
```
x = 1
```
by contrast, a value is dynamic if it depends on something that comes at runtime. E.g.
```
fn = \x -> add(x, 1)
```
we don't know what the result of `add(x, 1)` will be.
This change tracks static vs dynamic values so we can try to evaluate as much as possible in MatchlessToValue when we statically know the value.
This is mostly just a code clean up and I don't think it actually improves performance since we are generally converting from Expr => Value once during evaluation. If we could reify that it would be a savings (e.g. in code generation).
=> Add Scoped to MatchlessToValue to distinguish static from dynamic values.

core/src/main/scala/org/bykn/bosatsu/Matchless.scala, core/src/main/scala/org/bykn/bosatsu/MatchlessToValue.scala
Rather than requiring an allocation and making MatchString return a value, use the approach of SearchList which returns a bool and updates mutable variables on a match.
this was a TODO and before we implement codegen I'd like to try to fix issues with the Matchless AST.
=> Make MatchString a BoolExpr

core/src/main/resources/bosatsu/predef.bosatsu, core/src/main/scala/org/bykn/bosatsu/Predef.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/IntLaws.scala, test_workspace/AvlTree.bosatsu, test_workspace/BinNat.bosatsu, test_workspace/euler3.bosatsu, test_workspace/euler4.bosatsu
close #153 
see: https://www.hillelwayne.com/post/divide-by-zero/
for more discussion on this.
The main objection to this is that it hides errors. This is true. But without this (or a dependent type system) it becomes painful to deal with the optionality that is inherent in the `PositiveInt` or `Option[Int]` (which are kind of the same thing since PositiveInt is not closed under division, so you'd often wind up back at optionality).
=> fix div and mod issues related to #153

core/src/main/scala/org/bykn/bosatsu/Matchless.scala, core/src/test/scala/org/bykn/bosatsu/MatchlessTests.scala
close #509 
The Matchless scalacheck tests include something that is basically a fuzz test: send in totally random data and running twice on that should not throw and produce the same results.
The match error should not happen on typechecked code, but we are not fuzzing with typechecked code.
=> Fix match error in MatchlessTests due to fuzzing

core/src/main/scala/org/bykn/bosatsu/Externals.scala, core/src/main/scala/org/bykn/bosatsu/LetFreeEvaluation.scala, core/src/main/scala/org/bykn/bosatsu/Value.scala
I'm starting with the most invasive part of https://github.com/johnynek/bosatsu/pull/488. This creates a Value class that an Evaluator can either treat as a function (`asFn`) or it can pass it a let-free expression for a value so the external function can determine its own strategy for how to produce the output (which may not require full evaluation of the argument Value, eg it may use a cached return value).
=> Creates LetFreeExprFn for LetFreeEvaluation

cli/src/main/scala/org/bykn/bosatsu/PathModule.scala, cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala, cli/src/test/scala/org/bykn/bosatsu/codegen/python/CodeTest.scala, cli/src/test/scala/org/bykn/bosatsu/codegen/python/PythonGenTest.scala, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Identifier.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/Matchless.scala, core/src/main/scala/org/bykn/bosatsu/MatchlessFromTypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/MatchlessToValue.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/main/scala/org/bykn/bosatsu/Program.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala, core/src/test/scala/org/bykn/bosatsu/DeclarationTest.scala, core/src/test/scala/org/bykn/bosatsu/MatchlessTests.scala, core/src/test/scala/org/bykn/bosatsu/OperatorTest.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, core/src/test/scala/org/bykn/bosatsu/codegen/python/PythonGenTest.scala, test_workspace/Nat.bosatsu
This adds a `transpile` command to bosatsu, with one language (python) supported.
done items:
1. add tests with Jython that generated code runs.
2. add some tests for explicit constructs being compiled into specific code
3. try to minimize the code somewhat, some examples look a little verbose
This is not yet complete, and fails on a few inputs, but it is already large enough and has sufficient test coverage for an alpha quality merge.
I'll continue this week to get completeness and test coverage up.
=> Add python code generation

cli/src/test/scala/org/bykn/bosatsu/codegen/python/CodeTest.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala
we were only using Literal for True/False, but it was easily confused with Ident.
This add PyBool to make the AST more precise.
=> Add PyBool remove Code.Literal

cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala, cli/src/test/scala/org/bykn/bosatsu/codegen/python/CodeTest.scala, cli/src/test/scala/org/bykn/bosatsu/codegen/python/PythonGenTest.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala, core/src/test/scala/org/bykn/bosatsu/codegen/python/PythonGenTest.scala, test_workspace/StrConcatExample.bosatsu
This supports string patterns with substring matching.
There are some more improvements to the code used to generate python code including some utility functions that attempt to avoid branches where we statically know which one we are taking.
There is still a significant issue of over-use of bindings. Often bindings are made and used exactly once, or are only used by other bindings to initialize from. This is not a priority now as completeness and result correctness are the current focus.
=> Add python support for complex string patterns

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Test.scala
This logic to convert Value to Test in Evaluation looks generally useful. Does this seem like a reasonable move?
=> Refactor Value to Test conversion from Evaluation

cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala, cli/src/test/scala/org/bykn/bosatsu/codegen/python/PythonGenTest.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala, test_workspace/BUILD, test_workspace/List.bosatsu, test_workspace/ListPat.bosatsu
this is the last missing "instruction" from matchless to be able to compile to python.
This also adds code to run the bosatsu tests from Jython so we don't need to write tests twice.
There are still some todos with python however (the file names don't have .py, we aren't creating `__init__.py` files, and not all the external methods in Predef are implemented).
=> Implement SearchList for python

core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala, core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala, core/src/test/scala/org/bykn/bosatsu/pattern/SetOpsLaws.scala
normalizePattern was not working for lists, it was leaving names around.
I think this was the root cause of the #491 issues.
close #491
=> improve normalizePattern

cli/src/test/scala/org/bykn/bosatsu/codegen/python/CodeTest.scala, cli/src/test/scala/org/bykn/bosatsu/codegen/python/PythonGenTest.scala, core/src/main/resources/bosatsu/predef.bosatsu, core/src/main/scala/org/bykn/bosatsu/Predef.scala, core/src/main/scala/org/bykn/bosatsu/Value.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala, test_python.sh, test_workspace/Nat.bosatsu, test_workspace/Parser.bosatsu, test_workspace/PredefTests.bosatsu
1. add an example of a basic parser combinator library with bosatsu
2. add partition_String and rpartition_String to predef
3. fix a bug this uncovered in python.Code.Op rendering
=> Add a basic Parser example and partition to Predef

parser/.js/src/main/scala/org/bykn/bosatsu/parser/BitSet.scala, parser/.jvm/src/main/scala/org/bykn/bosatsu/parser/BitSet.scala, parser/src/main/scala/org/bykn/bosatsu/parser/Parser.scala, parser/src/test/scala/org/bykn/bosatsu/parser/ParserTest.scala
I think this basically gets us to feature parity with fastparse BUT the semantics are different: opt in backtracking vs opt out.
In my experience, this makes errors much more clear and discourages writing exponentially bad parsers.
=> Improve the parsing library a bit more

build.sbt, core/src/main/scala/org/bykn/bosatsu/LetFree.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, project/Dependencies.scala
replaces #590 
fixes an old todo to remove alley cats and use sortedmap (which has deterministic traversal order)
=> update to cats 2.2.0, remove alleycats

core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
make repeating a binding in a pattern an error #584 until such time as we solve the problem of equality in a generic way.
=> Error when bindings are duplicated in patterns

build.sbt, elmui/Makefile, elmui/build.sh, elmui/index.html
just add an exports object to index.html so module like code works. webpack would be a more complete solution but seems like overkill.
fixes https://github.com/johnynek/bosatsu/issues/594
=> Remove module configuration that broke browser imports

core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
@snoble noticed this:
https://github.com/johnynek/bosatsu/issues/574#issuecomment-704630538
but strangely it does not fail in the evaluation test. When I paste this in the browser it does fail.
So I guess that means the bug is in one of:
1. some difference in how the browser runs the code than how it is tested in CI. There are some null checks in the matchless code, but I don't think that is generally a problem.
2. the bug is somewhere after execution and this test isn't exercising the problem. But I don't see how that can be since the code does seem to fail when there are two globs in the browser.
@snoble if you have time to poke more at this, let me know if you find any more clues. I am not versed in how to use the browser developer tools to try to find infinite loops, etc...
=> Add a test noticed in issue 574

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala
Note this only changes the implementation of parsing, it doesn't change the intermediate language or the supported syntax.
=> directly add a Ternary ast node to parsing for better parsing test coverage

core/src/main/scala/org/bykn/bosatsu/LocationMap.scala
Since the code to compute col/row from offset was sent to cats-parse, but not the Doc dependent methods, we can remove some of that code here.
=> Use the LocationMap code moved to cats-parse

core/src/main/scala/org/bykn/bosatsu/CommentStatement.scala, core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/DefStatement.scala, core/src/main/scala/org/bykn/bosatsu/ExportedName.scala, core/src/main/scala/org/bykn/bosatsu/Identifier.scala, core/src/main/scala/org/bykn/bosatsu/Import.scala, core/src/main/scala/org/bykn/bosatsu/Indented.scala, core/src/main/scala/org/bykn/bosatsu/Json.scala, core/src/main/scala/org/bykn/bosatsu/ListLang.scala, core/src/main/scala/org/bykn/bosatsu/Lit.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/Operators.scala, core/src/main/scala/org/bykn/bosatsu/OptIndent.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageName.scala, core/src/main/scala/org/bykn/bosatsu/Padding.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/main/scala/org/bykn/bosatsu/StringUtil.scala, core/src/main/scala/org/bykn/bosatsu/TypeRef.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala, core/src/test/scala/org/bykn/bosatsu/OperatorTest.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, project/Dependencies.scala
replaces #648 
the scalafix got most of the way, but there were a few imports that were unneeded
cc @martijnhoekstra
=> Upgrade to cats-parse 0.3.0

core/src/main/scala/org/bykn/bosatsu/CommentStatement.scala, core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
Currently, Comment is not a NonBinding Declaration. As a result of that, any place that prohibits binding expressions or defs also prohibits comments.
This is really annoying.
The goal we have had so far, is be able to reconstruct the code from the parsed representation, or at least a formatted version of it.
The challenge is that means we have to store the comment in the AST somehow to do that.
=> Improving comments in Declaration

bosatsuj, build_native.sh, core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
There was a bug where if you use and enum, but only import the names of the constructors, you would get a confusing error message. This was due to a bad check in the TotalityChecker.
The check itself was redundant, and removing it seems to be a fix.
=> Fix an issue with imports and enums

core/src/main/scala/org/bykn/bosatsu/Import.scala, core/src/main/scala/org/bykn/bosatsu/rankn/TypeEnv.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
This is a continuation of #660 
That fix was only partial. I think this is a more complete fix.
=> Follow up to 660 on imported enum totality checks

core/src/main/resources/bosatsu/predef.bosatsu, core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/test/scala/org/bykn/bosatsu/DefRecursionCheckTest.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/PackageTest.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, core/src/test/scala/org/bykn/bosatsu/Regressions.scala, core/src/test/scala/org/bykn/bosatsu/TypedExprTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
allow `case` in match to harmonize with:
https://www.python.org/dev/peps/pep-0622/
this does not require case yet, just because it is a lot of work.
I do think visually this helps parse the parts of the block. Without case, it is parseable by machine, but starts to look like a sea of expressions to a human eye, IMO.
related to #623 #666
=> Allow case in match/recur

build.sbt
use the workaround described here:
https://github.com/scalapb/ScalaPB/issues/1024
Seems to work for me on an M1 laptop.
=> Use protocVersion 3.17.3 for M1 compatibility

core/src/main/scala/org/bykn/bosatsu/Matchless.scala
This reduces the `Nat.bosatsu` test file compiling to python from 252 lines to 234 lines. This is because we can avoid some checks on nat-like types (which were overlooked previously).
=> Use mustMatch parameter in Nat-like matching

cli/src/main/scala/org/bykn/bosatsu/CodeGenWrite.scala, cli/src/test/scala/org/bykn/bosatsu/codegen/python/CodeTest.scala, cli/src/test/scala/org/bykn/bosatsu/codegen/python/PythonGenTest.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala
close #765 
I also think I fixed the problems with the transient deadlocks in the test code. It seems Jython is not thread-safe and two different tests running concurrently could sometimes cause a deadlock.
I put any code accessing jython first acquiring a semaphore and it seems to fix the issue.
=> Fix Python staircasing, fix testing deadlock

core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/test/scala/org/bykn/bosatsu/TypedExprTest.scala
two cases were out of order, which resulted in problems with non-commutative situations.
=> Fix bug in TypedExpr.foldRight

core/src/test/scala/org/bykn/bosatsu/LocationMapTest.scala, project/Dependencies.scala
This makes type-check on the test_workspace directory about 10% faster.
=> Upgrade cats-parse to 0.3.5

core/src/main/scala/org/bykn/bosatsu/CommentStatement.scala, core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/DefStatement.scala, core/src/main/scala/org/bykn/bosatsu/Expr.scala, core/src/main/scala/org/bykn/bosatsu/Indented.scala, core/src/main/scala/org/bykn/bosatsu/OptIndent.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/test/scala/org/bykn/bosatsu/DeclarationTest.scala, core/src/test/scala/org/bykn/bosatsu/DefRecursionCheckTest.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/FreeVarTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, core/src/test/scala/org/bykn/bosatsu/TypedExprTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala, docs/language_guide.md, test_workspace/AvlTree.bosatsu, test_workspace/List.bosatsu
The idea here is in general there should only be one way to do things.
With blocks like:
```
x = (
y = 1
f(y)
)
```
We don't really need `def x:`.
This also has the nice side effect that `def` *always* defines a function now and has a more regular syntax: there is always a `(` after def.
This requires adding `external foo: Int` as a valid syntax for values, but that is more regular anyway, so I think that's fine.
=> Remove zero arg defs

core/src/main/scala/org/bykn/bosatsu/TypeParser.scala, core/src/main/scala/org/bykn/bosatsu/TypeRef.scala, core/src/main/scala/org/bykn/bosatsu/TypeRefConverter.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala
We previously could not directly parse into `Type` instead we parse into `TypeRef` and then convert in the context of the names imported in the source.
This refactors to share most of the same syntax but parsing a Type requires the fully qualified names (for things other than function or tuples).
=> Add parsing of Type

cli/src/main/scala/org/bykn/bosatsu/PathModule.scala, core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/TypeRef.scala, core/src/main/scala/org/bykn/bosatsu/TypeRefConverter.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala, core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala, core/src/test/scala/org/bykn/bosatsu/TypeRefTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala, jsapi/src/main/scala/org/bykn/bosatsu/jsapi/JsApi.scala
Since Type has skolems, metas and full package names, and TypeRef has none of these things, TypeRef was abused to get access to Document capabilities of TypeRef.
With #829 and #831 we added this capability to Type.
Here we removed almost all the unsoundness.
There is one wart here: parsing a meta is impossible because it has a mutable cell that is allocated in a monadic context. We can't do that while parsing so we allocate that cell to be null.
In practice this shouldn't be a problem since we only create meta variables during inference, and when inference succeeds, they should all be gone. It would be nice to find a way to statically verify that however.
=> Remove TypeRef.fromType, which created invalid TypeRefs

bench/src/main/scala/org/bykn/bosatsu/TestBench.scala, build.sbt, cli/src/main/scala/org/bykn/bosatsu/TypedExprToProto.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/Predef.scala, core/src/test/scala/org/bykn/bosatsu/PackageTest.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
cyclic dependencies can slow down the build and often point to confused design IMO.
=> Remove cyclic dependencies, re-enable acyclic

cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala, cli/src/test/scala/org/bykn/bosatsu/codegen/python/PythonGenTest.scala, core/src/main/scala/org/bykn/bosatsu/CollectionUtils.scala, core/src/main/scala/org/bykn/bosatsu/ExportedName.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala, core/src/main/scala/org/bykn/bosatsu/TypeRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/ValueToJson.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/CollectionUtilsTest.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala, core/src/test/scala/org/bykn/bosatsu/codegen/python/PythonGenTest.scala
the idea here is to specify different evaluators for pure values so we never have to admit impure or illegal functions into the bosatsu code.
The motivating example is IO. We could put literally no way to run IO directly in Bosatsu, so once you get an IO, you are stuck in IO land.
But when you compile, you can generate an IO evaluator for your program, and if you run that program you could then do impure things, but evaluating pure Bosatsu code is never impure (even though a bosatsu program may be a builder of another impure program).
=> Add Evaluators to transpiler

bench/src/main/scala/org/bykn/bosatsu/TestBench.scala, cli/src/main/scala/org/bykn/bosatsu/PathModule.scala, cli/src/test/scala/org/bykn/bosatsu/TestProtoType.scala, core/.js/src/main/scala/org/bykn/bosatsu/Par.scala, core/.jvm/src/main/scala/org/bykn/bosatsu/Par.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/MatchlessFromTypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/MemoryMain.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/PackageTest.scala, core/src/test/scala/org/bykn/bosatsu/ParTest.scala, core/src/test/scala/org/bykn/bosatsu/Regressions.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
clean up some TODOs around use of ExecutionContext in a way that is clean for scalajs and jvm.
=> remove use of ExecutionContext.global

core/src/main/scala/org/bykn/bosatsu/DefStatement.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/MemoryMain.scala, core/src/main/scala/org/bykn/bosatsu/OptIndent.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/UnusedLetCheck.scala, core/src/main/scala/org/bykn/bosatsu/ValueToDoc.scala, core/src/main/scala/org/bykn/bosatsu/ValueToJson.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala, core/src/main/scala/org/bykn/bosatsu/rankn/DefinedType.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
(and some other indentation fixes that were confusing the scala 3 parser).
=> use literal type lambda for scala 3 compatibility

cli/src/main/scala/org/bykn/bosatsu/TypedExprToProto.scala, core/src/main/scala/org/bykn/bosatsu/ExportedName.scala, core/src/main/scala/org/bykn/bosatsu/NameKind.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/Referant.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/main/scala/org/bykn/bosatsu/rankn/ConstructorFn.scala, core/src/main/scala/org/bykn/bosatsu/rankn/DefinedType.scala, core/src/main/scala/org/bykn/bosatsu/rankn/TypeEnv.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/MatchlessTests.scala
ConstructorFn has some codesmell that so far was ignored. For instance, it carries its full type, but that type is actually ignored by serialization.
Secondly, we require to know the full type of the constructor for all `TypeEnv[A]` but we actually only query that type once we have fully inferred types (currently that means A =:= Variance in practice).
In the work to check (or infer) Kinds, we wouldn't know the full Kind of generic type parameters at SourceConverter time, and only later at Infer time. This currently presents a problem, but it is only a problem due to how the code is factored, not an actual problem with the algorithms.
relates to #121
=> Simplify ConstructorFn

core/src/main/scala/org/bykn/bosatsu/Expr.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala, core/src/main/scala/org/bykn/bosatsu/UnusedLetCheck.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
This just unifies Lambda and AnnotatedLambda by making the type Option. This nets less code.
I'm about to make another change to Expr so I thought I'd do this first.
=> Simplify Expr by removing annotated Lambda

core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/DefStatement.scala, core/src/main/scala/org/bykn/bosatsu/Expr.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala, core/src/main/scala/org/bykn/bosatsu/TypeRef.scala, core/src/main/scala/org/bykn/bosatsu/UnusedLetCheck.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/DeclarationTest.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
close #938 
This turns out to be needed to make kinds work with many of our current examples (which do have types mentioned which are not of kind `*`).
The change is pretty mechanical and minor.
We cannot use any kind of strict checking that all free vars are mentioned like we do with structs/enums because unlike structs and enums `defs` are recursive. We assume any param not mentioned is free in the higher level until we reach the top and then it is a top level free param.
=> Add syntax for def type annotation

core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
I was looking at #650 
but I can't seem to get any of the examples to fail.
I don't know why. I have a few theories:
1. since I track the variance of all types, I can see that `List[forall a. a -> a]` and `forall a. List[a -> a]` are the same type, but maybe without variance you can't?
2. the type system is unsound so we are accepting invalid programs
3. there are bugs in the current implementation, but not exactly soundness problems
I couldn't get any real programs to fail with #267 either. All the examples I tried either involved uninhabited types that I couldn't write with programs that didn't ignore bindings, or they just worked.
=> Add quick look tests

core/src/main/scala/org/bykn/bosatsu/Referant.scala, core/src/main/scala/org/bykn/bosatsu/TypeParser.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Ref.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/main/scala/org/bykn/bosatsu/rankn/TypeEnv.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
close #264 and #267
I think this and the other variance related changes address all of the issues in #264  we can reopen later if not.
The pushdownCovariant idea can be taken further I think. The current algorithm is only catching easy, not all cases. And we can possibly use it in more than just inferring types on matches.
cc @snoble
=> Improve inference of types containing forall and matching.

core/src/main/scala/org/bykn/bosatsu/PackageError.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
that error was wrongly labeled as an InternalError. It's not. It can happen from user code.
Still the message isn't very diagnostic, but at least it isn't toString on an AST.
=> Improve UnexpectedMeta error

core/src/main/scala/org/bykn/bosatsu/MainModule.scala
There are basically two modes you can run in:
1. compile only mode where we can use interface files as dependencies
2. runtime capable mode, where we cannot use interfaces and we need the full code.
All the modes of the compiler are in one of those two modes. One could imagine that in the long run, 1. could go away. If you add macros or dependent types, we need the full code at type-checking time (maybe a good reason not to do those things!)
This code is quite junky now and would be much nicer if we could get to #197
=> Refactor MainModule inputs

base/src/main/scala/org/bykn/bosatsu/Macro.scala, core/src/main/scala/org/bykn/bosatsu/Predef.scala
I tried to get this to not show up as an error in metals, but it seems the problem is metals shares state across different starts, so starting metals in one project will set the working directory for metals in other projects.
=> Improve the source embedding macro

core/src/main/resources/bosatsu/predef.bosatsu, core/src/main/scala/org/bykn/bosatsu/Declaration.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/PackageError.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, test_workspace/AvlTree.bosatsu, test_workspace/BinNat.bosatsu, test_workspace/List.bosatsu, test_workspace/Nat.bosatsu, test_workspace/Queue.bosatsu, test_workspace/Quicksort.bosatsu, test_workspace/TreeList.bosatsu, test_workspace/dicttools.bosatsu, test_workspace/euler7.bosatsu, test_workspace/recordset.bosatsu
this is the main syntax change in #1026. We can do this before changing the type-system to have FunctionN types.
=> Require parens on dot apply

core/src/main/scala/org/bykn/bosatsu/Expr.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
This changes to require that all expressions being type checked by Infer have no free type variables. The caller needs to put the bounds in the correct places by using `Generic(_, _)`. This is done in SourceConverter rather than spreading the logic around.
=> Simplify and unify free type variable handling

core/src/main/scala/org/bykn/bosatsu/Expr.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
This make monomorphization very hard (if not impossible) but removing this if we decide we really want monomorphization can be done.
In the mean time, I'm interested in exploring more powerful recursions that still provable terminate, and some examples I've hit require polymorphic recursion.
=> Support polymorphic recursion

core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala, core/src/test/scala/org/bykn/bosatsu/DefRecursionCheckTest.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
replaces #1022 
The idea here is that we can recurse on arguments to functions which are themselves allows (substructures).
This allows us to implement functor type things (because to encode those we need existential types, which are encoded as continuations).
=> Support recursion in continuations

core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/ParallelViaProduct.scala, test_workspace/Eval.bosatsu
I wanted to try implementing cats.Eval now that we have polymorphic recursion #1041 .
I couldn't see a way to do it without a poor version of the fuel pattern: promise up front how many recursions you would do at most.
But along the way, I noticed that we are only returning one error message from any branch in the code in DefRecursionCheck, so I implemented a version of the idea in #1044 which allowed me to see all the error messages at once (when they are on parts of the code I was already traversing).
=> Improve error messages in DefRecursionCheck, Eval example

core/src/main/scala/org/bykn/bosatsu/Expr.scala, core/src/main/scala/org/bykn/bosatsu/ListUtil.scala, core/src/main/scala/org/bykn/bosatsu/PackageError.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/ExprTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ListUtilTest.scala
I wanted to merely improve error reporting by showing more than one type error when it was possible (#1044 )
Along the way, I found a long standing bug with locations incorrectly being set to be their outermost scope. I had noticed this before, but hadn't run it down. I had assumed it was part of typechecking and just due to inference being a bit non-specific when unifying across many types.
But in my example, I wound up printing out the Expr and seeing that the Declarations and Regions were set wrong.
The bug turned out to be the `.as` from `Functor`. The Expr traverse instance is doing what you say, but .as isn't what we meant. We wanted to only replace the outermost tag, not every tag transitively.
I have removed that code since we were only using it for this one bug. :)
This also …
=> Fix long bug in error regions

core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
it is *very* concerning that changing these directions (widening instead of narrowing) doesn't require changing any tests.
I should probably try to find some example that fails in the previous direction... I guess it is actually very rare for subsCheck to not be just unifying the code into a single type rather than instantiating.
Or it could be that we just don't have any way of failing after coerce since we just assume the types are right after that so changing them can't change the tests... but it seems like we should be able to find some code that didn't type before that does now?
=> Fix coerce in Infer.subsCheck

core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
I don't think loops in the TyMeta graph actually cause a problem, but avoiding them isn't difficult, and makes things a bit simpler to reason about.
=> Ensure no meta loops in Infer

core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala
This is towards supporting existential types. Currently many functions are spreading out the handling of quantification by calling skolemize and unskolemize in two different places. This is trying to get them all collocated so we can add support for existential types more easily.
In any case it seems a good change, although the abstractions used are a bit heavier than I would like (use of FunctionK in scala isn't so elegant).
=> Refactor calls to skolemize in Infer

cli/src/main/protobuf/bosatsu/TypedAst.proto, cli/src/main/scala/org/bykn/bosatsu/TypedExprToProto.scala, core/src/main/scala/org/bykn/bosatsu/KindFormula.scala, core/src/main/scala/org/bykn/bosatsu/Shape.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/main/scala/org/bykn/bosatsu/TypeParser.scala, core/src/main/scala/org/bykn/bosatsu/TypeRef.scala, core/src/main/scala/org/bykn/bosatsu/TypeRefConverter.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/TypedExprNormalization.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/KindParseTest.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala, core/src/test/scala/org/bykn/bosatsu/TypeRefTest.scala, core/src/test/scala/org/bykn/bosatsu/TypedExprTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/NTypeGen.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala, test_workspace/BuildLibrary.bosatsu
=> Existential types support

core/src/main/scala/org/bykn/bosatsu/PackageError.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala, test_workspace/recordset.bosatsu
There were actually two bugs here:
1. we were checking if either kind subsumed the other, which makes no sense.
2. there was also a bug: `Kind.leftSubsumesRight(kind2, kind2)` which always returns true so the check was a no-op.
Fixing the bug exposed some issues with the super complexly typed RecordSet code.
=> Fix bug in kind checking of patterns

core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/pattern/SeqPattern.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/PatternTest.scala, core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala, core/src/test/scala/org/bykn/bosatsu/pattern/SeqPatternTest.scala
since adding Char literals and patterns in #1052 it seems StrPat.isTotal was broken, and therefore, pattern intersection.
A scalacheck finally detected it by noticing that intersection wasn't associative.
Yah for scalachecks and laws!
=> Fix StrPat.isTotal

core/src/main/resources/bosatsu/predef.bosatsu, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/main/scala/org/bykn/bosatsu/Predef.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/main/scala/org/bykn/bosatsu/Value.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/KindFormulaTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/NTypeGen.scala, core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala, docs/src/main/paradox/language_guide.md
relates to #1026 #1029 
If we only have functions up to 32, then we can only have types with up to 32 parameters (otherwise their constructors are unrepresentable). So, this removes the cons-cell encoding of variadic tuples and adds 32 concrete tuples.
This should improve runtime performance of tuple heavy code, but I have not benchmarked it.
I could also have implemented this by adding the types and constructor functions directly to the post-source converted code. That may improve test performance (that winds up compiling the predef a lot, but in practice I don't think it would matter, plus it hides the structure and name of the parameters in a harder to see place and makes more types magical).
=> define tuples up to 32

cli/src/test/scala/org/bykn/bosatsu/codegen/python/PythonGenTest.scala, core/src/main/scala/org/bykn/bosatsu/Matchless.scala, core/src/main/scala/org/bykn/bosatsu/MatchlessToValue.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala
In order to implement a backend on a platform without built-in closures (such as a C backend), it is better to explicitly build the context over which the lambdas close over, and also to insure that it only reaches into the current scope (not across several scopes).
This PR makes that change.
This doesn't really help python code generation or the interpreter (both of which use the Matchless IR). But it does open the door to easier implementation of a C or Java backend.
=> Explicitly build closure captures

cli/src/main/scala/org/bykn/bosatsu/TypedExprToProto.scala, core/src/main/scala/org/bykn/bosatsu/rankn/DefinedType.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Type.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala, core/src/test/scala/org/bykn/bosatsu/rankn/NTypeGen.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala
This is an invariant I realized we were losing. since `(forall x. C[x])[y] == (forall x. C[x, y])` we can always push formal out of TyApply and keep the left hand side a Rho type.
This makes it easier to reason about the types, but also does a minor performance improvement in Infer since we can leverage that the left is a Rho without having to pattern match again.
=> Remember the TyApply is always on a Rho

core/src/main/scala/org/bykn/bosatsu/KindFormula.scala, core/src/main/scala/org/bykn/bosatsu/PackageError.scala, core/src/main/scala/org/bykn/bosatsu/Shape.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
=> Improve KindFormula.Error reporting

cli/src/main/protobuf/bosatsu/TypedAst.proto, cli/src/main/scala/org/bykn/bosatsu/TypedExprToProto.scala, core/src/main/scala/org/bykn/bosatsu/Kind.scala, core/src/test/scala/org/bykn/bosatsu/KindParseTest.scala
this is just to save a few bytes in the proto since most commonly we just have a few kinds, and those can be represented by 1 byte in almost all common cases.
=> Encode Kinds to Longs in proto

core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/pattern/SeqPattern.scala, core/src/main/scala/org/bykn/bosatsu/pattern/SetOps.scala, core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala, core/src/test/scala/org/bykn/bosatsu/pattern/SeqPatternTest.scala
=> Fix intersection commutativity 1086

core/src/main/resources/bosatsu/predef.bosatsu, core/src/main/scala/org/bykn/bosatsu/Predef.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala, test_workspace/PredefTests.bosatsu, test_workspace/Properties.bosatsu, test_workspace/Rand.bosatsu, test_workspace/Xoshiro256starstar.bosatsu
this gives an example of a basic property testing library for bosatsu.
Hopefully this makes it easier to write more powerful tests directly in bosatsu.
=> Add basic property testing

core/src/main/scala/org/bykn/bosatsu/pattern/SeqPattern.scala, core/src/main/scala/org/bykn/bosatsu/pattern/SetOps.scala, core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala, core/src/test/scala/org/bykn/bosatsu/pattern/SeqPatternTest.scala, core/src/test/scala/org/bykn/bosatsu/pattern/SetOpsLaws.scala
I tried to fix #1108 but I couldn't find a fix. It's not a real bug exactly since TotalityTest checks the laws on ill-typed patterns and the pattern in question is ill-typed.
A probably better test for TotalityCheck would be to generate well-typed patterns only, and we could probably find more issues that way.
I did find a few minor things that seemed like improvements, but since no tests changed, maybe they aren't better. Who knows.
=> Attempt to fix 1108

core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala, core/src/main/scala/org/bykn/bosatsu/pattern/SeqPart.scala, core/src/main/scala/org/bykn/bosatsu/pattern/SeqPattern.scala, core/src/main/scala/org/bykn/bosatsu/set/Rel.scala, core/src/main/scala/org/bykn/bosatsu/set/Relatable.scala, core/src/main/scala/org/bykn/bosatsu/set/SetOps.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/TotalityTest.scala, core/src/test/scala/org/bykn/bosatsu/pattern/SeqPatternTest.scala, core/src/test/scala/org/bykn/bosatsu/pattern/StringSeqPatternSetLaws.scala, core/src/test/scala/org/bykn/bosatsu/rankn/TypeTest.scala, core/src/test/scala/org/bykn/bosatsu/set/RelLaws.scala, core/src/test/scala/org/bykn/bosatsu/set/SetOpsLaws.scala
The idea here is to use the UnionRelModule to improve relation computation for Patterns.
Computing the relationships of patterns in the presence of nested unions and non-normalized representations is pretty challenging.
The UnionRelModule allows you to have a recursive structure that is well tested. So you only have to solve simpler problems and be sure it's correct.
This and the added test coverage wound up fixing some lurking bugs in the original set relationship calculations on Patterns, but since TotalityCheck is only a compilation lint, the bugs could only have manifested by a runtime error of a non-total pattern match (which I never saw so far).
=> leverage UnionRelatable

core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala
Since function parameter names shadow the same in python and bosatsu, we can escape those directly rather than allocating new ones to simulate the scoping rules.
Here is a small diff:
```
--- pyout/Bosatsu/BinNat.py	2024-02-03 11:40:29
+++ pyout_new/Bosatsu/BinNat.py	2024-02-03 11:27:31
@@ -2,188 +2,180 @@
import Bosatsu.Predef as ___iPredef1
import unittest as ___iunittest2
-def ___btoInt0(___bb1):
-    if ___bb1[0] == 0:
+def toInt(b):
+    if b[0] == 0:
return 0
-    elif ___bb1[0] == 1:
-        ___bn2 = ___bb1[1]
-        return (___btoInt0(___bn2) * 2) + 1
+    elif b[0] == 1:
+        ___bn0 = b[1]
+        return (toInt(___bn0) * 2) + 1
else:
-        ___bn3 = ___bb1[1]
-        return (___btoInt0(___bn3) * 2) + 2
-toInt = ___btoInt0
+        ___bn1 = b[1]
+        return …
```
=> Improve python code gen for top level names

cli/src/test/scala/org/bykn/bosatsu/codegen/python/CodeTest.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala
Here is an example:
```
def log2(i):
-    ___t64 = 0 < i
-    ___t65 = 0
-    ___t66 = i
-    ___t67 = 0
-    while ___t64:
-        ___t65 = (lambda n, cnt: (n // 2, cnt + 1))(___t66, ___t67)
-        ___t68 = ___t65[0]
-        ___t67 = ___t65[1]
-        ___t64 = (0 < ___t68) and (___t68 < ___t66)
-        ___t66 = ___t68
-    return ___t67
+    ___t16 = 0 < i
+    ___t17 = 0
+    ___t18 = i
+    ___t19 = 0
+    while ___t16:
+        ___t20 = ___t18 // 2
+        ___t19 = ___t19 + 1
+        ___t16 = (0 < ___t20) and (___t20 < ___t18)
+        ___t18 = ___t20
+    return ___t19
```
In the `int_loop` built-in function, we often wind up with `(lambda x, y: ...)(x_arg, y_arg)` patterns, which could be inlined. Also, in this example, we know we are returning a tuple2. So, we can try to …
=> Inline applying lambda in Python code generation

core/src/main/scala/org/bykn/bosatsu/ListUtil.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageError.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/ListUtilTest.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
close #446 
Before this PR, if an example with a case match and missing some fields gave:
```
oscar@Patricks-MacBook-Air bosatsu % bosatsu type-check --input_all_subdir test_workspace --package_root test_workspace
in file: test_workspace/AvlTree.bosatsu:36:29, package AvlTree
missing field height in Branch Branch {size: s }
34|    match t:
35|        Empty: 0
36|        Branch { size: s }: s
^
in file: test_workspace/AvlTree.bosatsu:36:29, package AvlTree
missing field key in Branch Branch {size: s }
34|    match t:
35|        Empty: 0
36|        Branch { size: s }: s
^
in file: test_workspace/AvlTree.bosatsu:36:29, package AvlTree
missing field left in Branch Branch {size: s }
34|    match t:
35|        Empty: 0
36|        Branch { size: s }: s
^
in file: …
```
=> Fix issue 446

cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala, test_workspace/BinNat.bosatsu, test_workspace/Nat.bosatsu, test_workspace/Queue.bosatsu, test_workspace/Rand.bosatsu
This is trying to exercise the property check API a bit, and of course the language at the same time.
=> Add a Bosatsu/Queue property check

core/src/main/scala/org/bykn/bosatsu/CommentStatement.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/Padding.scala, core/src/main/scala/org/bykn/bosatsu/Parser.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala
this allows comments in headers, but discards them: it does not retain them in the parsed AST.
This is convenient when we are really strict about imports and exports.
=> Support comments in headers

cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala, test_workspace/BinNat.bosatsu, test_workspace/Nat.bosatsu, test_workspace/Queue.bosatsu, test_workspace/Rand.bosatsu
trying to exercise property checks by adding more checks for Queue. Definitely it can be tricky to implement functions in Bosatsu due to the totality requirements. For instance, implementing Rand::one_of was a bit tricky. You have to find the right recursion strategy. I was trying to make sampling O(log N), so I needed to make a tree. To do that, I used BinNat to be able to recur on half the size of the items, rather than the naive approach.
I also found a nice trick.
Define:
```
external def todo(ignore: x) -> forall a. a
```
then we can consume args and magically produce things by doing `todo((foo, bar))` and run `type-check`. Then it fails at runtime since we don't actually implement todo. We could use this strategy except possibly make that function only exist in predef when running …
=> add complete queue property checks

core/src/test/scala/org/bykn/bosatsu/ShapeTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala, test_workspace/AvlTree.bosatsu, test_workspace/BinNat.bosatsu, test_workspace/Nat.bosatsu, test_workspace/NumberProps.bosatsu, test_workspace/Properties.bosatsu
add the same tests for BinNat as Nat.
=> Add property checks for BinNat

core/src/main/scala/org/bykn/bosatsu/Matchless.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala, core/src/test/scala/org/bykn/bosatsu/MatchlessTests.scala, test_workspace/BinNat.bosatsu
close #1181 
This bug has been lurking in python code generation for some time, but only with generative testing did we push hard enough to find it.
=> Fix bug in python if/else chains

core/src/main/scala/org/bykn/bosatsu/MainModule.scala, docs/src/main/paradox/getting_started.md
=> Rename type-check to check

cli/src/main/scala/org/bykn/bosatsu/PathModule.scala, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Test.scala, jsui/src/main/scala/org/bykn/bosatsu/jsui/Store.scala
related to #1180
Just using parallelism doesn't work because MatchlessToValue uses mutable state and it seems that threading breaks.
Considering how to make that work when values can be evaluated in parallel requires some thought. Probably using Eval at all won't work, and we will need something smarter.
=> Change test evaluation

core/src/main/scala/org/bykn/bosatsu/DefRecursionCheck.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageError.scala, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/main/scala/org/bykn/bosatsu/Statement.scala, core/src/main/scala/org/bykn/bosatsu/TypeRefConverter.scala, core/src/main/scala/org/bykn/bosatsu/rankn/Infer.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, core/src/test/scala/org/bykn/bosatsu/rankn/RankNInferTest.scala
close #1170 
This does a few things:
1. allows external def to have type parameters. This allows setting the kinds on the type parameters other than kind `*`.
2. error if the type parameters do not exactly match the free types in the external def.
3. verify that the final type of the external def is well kinded. Previously, we just took parsed syntax and accepted whatever was claimed, but that allowed to make values of the wrong kind.
=> Improve external def parsing

test_workspace/Nat.bosatsu, test_workspace/NumberProps.bosatsu
just another exercise.
With Nat, linear depth recursion will overflow the stack, so the #1172 would be very useful.
=> Add Nat::divmod

core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala
the pattern:
```
if x matches p:
trueCase
else:
falseCase
```
was being compiled into:
```
b = match x:
case p: True
case _: False
match b:
case True: trueCase
case False: falseCase
```
rather than relying on optimization later, it's easy to detect this pattern while still at the source AST and directly convert to:
```
match x:
case p: trueCase
case _: falseCase
```
=> Optimize if-matches case

cli/src/main/scala/org/bykn/bosatsu/TypedExprToProto.scala, cli/src/test/scala/org/bykn/bosatsu/TestProtoType.scala, core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Import.scala, core/src/main/scala/org/bykn/bosatsu/ImportMap.scala, core/src/main/scala/org/bykn/bosatsu/ImportedName.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/MatchlessFromTypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/NameKind.scala, core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageCustoms.scala, core/src/main/scala/org/bykn/bosatsu/PackageError.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/MatchlessTests.scala, core/src/test/scala/org/bykn/bosatsu/Regressions.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
I noticed if I made a duplicate import that does not exist to a name that collides with a predef name, the error message is bad.
I should add a test exercising this error message to be sure. There were two things:
1. we didn't see both imports, just one.
2. the predef import said "unknown source" which means that we need to handle predef separately in error messages.
=> Improve duplicate imports

core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala
the python code generation was often generating code like:
```python
foo = bar
baz = foo
return baz
```
which is annoying to read and less efficient for python to execute. This simplifies chains like this to avoid the needless bindings.
=> simplify python code generation return statements

core/src/main/scala/org/bykn/bosatsu/Lit.scala, core/src/main/scala/org/bykn/bosatsu/Matchless.scala, core/src/main/scala/org/bykn/bosatsu/MatchlessToValue.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/StringUtil.scala, core/src/main/scala/org/bykn/bosatsu/TotalityCheck.scala, core/src/main/scala/org/bykn/bosatsu/TypedExprNormalization.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala, core/src/main/scala/org/bykn/bosatsu/pattern/Matcher.scala, core/src/main/scala/org/bykn/bosatsu/pattern/SeqPattern.scala, core/src/main/scala/org/bykn/bosatsu/pattern/Splitter.scala, core/src/main/scala/org/bykn/bosatsu/pattern/StrPart.scala, core/src/test/scala/org/bykn/bosatsu/Gen.scala, core/src/test/scala/org/bykn/bosatsu/ParserTest.scala, core/src/test/scala/org/bykn/bosatsu/pattern/SeqPatternTest.scala, core/src/test/scala/org/bykn/bosatsu/pattern/StrPartTest.scala, core/src/test/scala/org/bykn/bosatsu/pattern/StringSeqPatternSetLaws.scala
I noticed we are generating code for static string matches that could be done in advance.
This refactors to use the existing string matching code statically.
=> evaluate static string matches in TypedExprNormalization

core/src/main/scala/org/bykn/bosatsu/codegen/python/Code.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala, test_workspace/Char.bosatsu
I am mostly doing this to just practice improving code generation on an easier target than C. Since I can run the tests under python I have good confidence the changes make sense. Also, the generated code is fairly easy to read.
With this PR, these examples:
```
def starts_with_foo(s): s matches "foo${_}"
def ends_with_foo(s): s matches "${_}foo"
def contains_foo(s): s matches "${_}foo${_}"
def contains_foo_bar(s): s matches "${_}foo${_}bar${_}"
```
compile to:
```python
def starts_with_foo(s):
___t14 = 0
return s.startswith("foo", 0)
def ends_with_foo(s):
___t15 = 0
return s.endswith("foo")
def contains_foo(s):
___t16 = 0
return "foo" in s
def contains_foo_bar(s):
___t17 = 0
___t18 = 0
___t19 = False
___t20 = s.find("foo", ___t18)
if ___t20 > -1:
___t21 = ___t20 + 3
if s.find("bar", …
```
=> More improvements to MatchString codegen on Python

test_workspace/Rand.bosatsu
it's possible to add optimizations to do this, but no reason to rely on that when we know we are doing power of 2 division.
=> Remove some divisions from random number generation

.github/workflows/ci.yml, c_runtime/bosatsu_runtime.c, cli/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala, core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangGen.scala, core/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala, test_workspace/BinNat.bosatsu, test_workspace/IntTest.bosatsu
in a while loop, we need to atomically update the variables. In python we do this with tuple assignment, but here we were just iteratively assigning, but if a previous assignment updated a value we later need, that caused a bug.
The solution I made was assign everything to a temp variable, then assign all the temp variables to the loop variables.
=> Fix BinNat on C fixing a while loop compilation issue

.github/workflows/ci.yml, c_runtime/bosatsu_runtime.c, c_runtime/bosatsu_runtime.h, cli/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala, core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangGen.scala, core/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala, test_workspace/IntTest.bosatsu, test_workspace/Properties.bosatsu
There are two bugs fixed here (sorry)...
1. the shifting code wasn't using twos compliment (I am having second thoughts about using a sign + magnitude representation, but as long as it is here, for negative numbers we need to convert to twos compliment for bitwise ops).
2. if a closure is used in a nested recursive position, we were incorrectly allocating the value for it. This can happen rarely when the optimizer rewrites a function call to being nested. This seems to be due to an optimization that we push down calls as low as we need them, which can result in pushing them into nested calls. Maybe we don't want to push values down since it can also wind up multiplying work and de-optimizing calls (e.g. imagine `let x = expensive(y) in z.map(w -> (w, x))` here we don't want to push x down …
=> Fix bug with shifts and recursive closures

cli/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala, core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangGen.scala
since we lift MakeStruct, MakeEnum, NatSucc into lambdas when they are not directly applied, we can generate duplicate functions that are equivalent if those items appear more than once in generated code.
This avoids that to simplify code generation when inspecting the output, I assume any C compiler would be good enough to optimize this from a performance perspective.
=> Cache function declaration to avoid generating duplicate functions

cli/src/test/scala/org/bykn/bosatsu/PathModuleTest.scala, cli/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala, core/src/main/scala/org/bykn/bosatsu/Matchless.scala, core/src/main/scala/org/bykn/bosatsu/MatchlessToValue.scala, core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangGen.scala, core/src/main/scala/org/bykn/bosatsu/codegen/clang/Code.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala, core/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala
this closes #770 by moving a lot of the logic of while construction into a single place, then generate while loops after. This unifies 3 implementations (MatchlessToValue, python, c).
It also opens the door to possibly remove the SearchList node since I think that can be rewritten as a while loop.
=>  add while to matchless

.gitignore, c_runtime/Makefile, c_runtime/Makefile.test, c_runtime/bosatsu_ext_Bosatsu_l_Predef.c, c_runtime/bosatsu_generated.h, c_runtime/bosatsu_runtime.c, c_runtime/bosatsu_runtime.h, c_runtime/test.c, c_runtime/typegen.py, cli/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala, core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangGen.scala, core/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala
in #1298 I was trying to leverage the fact that all objects are immutable and form a DAG to justify reference counting.
Doing this correctly is a significant challenge, but also it makes the code much more complex. My reading of the GC literature is that it is actually very hard to make reference counting perform as well as GC and its conceptual simplicity is appealing, but a mirage. I've seen reports the tail GC time of ref counting (which still exists when large dags fall out of scope) is also very large, but since most objects don't get many references and are almost immediately collected, you are doing a lot of extra work (maybe 30-50%) not to mention making the code harder for the c compiler to optimize.
I can always come back to this if I want to continue, but it seems wise to just …
=> try boehm gc

cli/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/TypedExprNormalization.scala
if we have:
```python
x = f(y)
z -> (x, z)
```
it looks like you could inline `x = f(y)` but the problem is we have no idea how many times the lambda will be called. By moving that in we could massively blow up function run time since a constant may not be un-cached. This also changes what closures close over. Without a good reason to do this, it shouldn't be the default.
I noticed some code being generated that surprised me due to this behavior.
=> Don't inline Apply across lambdas

core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
The original code was keeping any *package* we depend on, but at final code generation stage we only need to keep the values.
=> Fix tree shaking graph edge code

test_workspace/FibBench.bosatsu, test_workspace/Prog.bosatsu
comparing python on 37:
```
took seconds 4.24458909034729
>>> fib(37)
39088169
```
bosatsu C:
```
oscar@patricks-air bosatsu % time c_out/test_exe 37
fib(37) = 39088169
c_out/test_exe 37  0.13s user 0.00s system 98% cpu 0.132 total
```
or 32x faster. Both of these implementations are using naive fib big integers, so this is really a silly benchmark of function call and big int addition.
We can go bigger and overflow int32 (which we use when numbers are small)
```
oscar@patricks-air bosatsu % time c_out/test_exe 47
fib(47) = 4807526976
c_out/test_exe 47  12.56s user 0.03s system 99% cpu 12.615 total
```
=> Make a simple fib computing program for naive benchmarks

README.md, cli/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala, core/src/main/resources/bosatsu/predef.bosatsu, core/src/main/scala/org/bykn/bosatsu/SourceConverter.scala, core/src/test/scala/org/bykn/bosatsu/EvaluationTest.scala, core/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala, docs/src/main/paradox/index.md, test_workspace/AvlTree.bosatsu, test_workspace/BinNat.bosatsu, test_workspace/List.bosatsu, test_workspace/Prog.bosatsu, test_workspace/Queue.bosatsu, test_workspace/TreeList.bosatsu, test_workspace/bazel_deps_api.bosatsu, test_workspace/dicttools.bosatsu, test_workspace/euler1.bosatsu, test_workspace/euler2.bosatsu, test_workspace/euler7.bosatsu
close https://github.com/johnynek/bosatsu/issues/1235
=> Rename foldLeft to foldl_List

cli/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala, core/src/main/scala/org/bykn/bosatsu/Pattern.scala, core/src/main/scala/org/bykn/bosatsu/TypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/TypedExprNormalization.scala, core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangGen.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala, core/src/test/scala/org/bykn/bosatsu/PatternTest.scala, core/src/test/scala/org/bykn/bosatsu/TypedExprTest.scala, core/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala
close #1126
This properly handles masking by renaming so that substitution can always proceed. This opened up three optimizations in the tests, but in real code the kind of shadowing this is dealing with may not often happen, so I don't know if it matters much.
(I should really do this with a real benchmark suite).
=> Improve TypedExpr.substitute issue 1126

core/src/main/scala/org/bykn/bosatsu/Package.scala, core/src/main/scala/org/bykn/bosatsu/PackageMap.scala
trying to get towards improving the cli to compile C generated code, and I want to simplify some.
I'm rethinking the idea of always normalizing packages on compile since that normalization is expensive but also probably doesn't help python or the interpreter much.
It would help a compiled language with an optimizer since we can apply optimizations at the bosatsu layer that lower layers can't do (since they don't know the invariants).
=> refactor Package and PackageMap some

cli/src/main/scala/org/bykn/bosatsu/IOPlatformIO.scala, cliJS/src/main/scala/org/bykn/bosatsu/Fs2PlatformIO.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/MemoryMain.scala, core/src/main/scala/org/bykn/bosatsu/PlatformIO.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala, jsapi/src/main/scala/org/bykn/bosatsu/jsapi/JsApi.scala, jsui/src/main/scala/org/bykn/bosatsu/jsui/Store.scala
really PlatformIO should abstract over a real filesytem and not be too vague and pretend like there maybe not even such thing as directories. Simulating that in memory isn't too much more work, so just do it.
=> Remove optional ops from PlatformIO

proto/src/main/protobuf/bosatsu/TypedAst.proto
=> Add Library to proto definition

core/src/main/scala/org/bykn/bosatsu/hashing/Algo.scala, core/src/main/scala/org/bykn/bosatsu/library/Command.scala, core/src/main/scala/org/bykn/bosatsu/library/LibConfig.scala, core/src/main/scala/org/bykn/bosatsu/tool/PackageResolver.scala
this doesn't do any linking, just checking compilation.
To deal with libraries correctly in test and build we need to re-implement the compilers to not use an identifier which is (PackageName, Identifier), but for packages that are imported more than once use (Library, Version, PackageName, Identifier)... this will be a somewhat major refactor that is next up.
=> Add lib check command

core/src/main/scala/org/bykn/bosatsu/Evaluation.scala, core/src/main/scala/org/bykn/bosatsu/Matchless.scala, core/src/main/scala/org/bykn/bosatsu/MatchlessFromTypedExpr.scala, core/src/main/scala/org/bykn/bosatsu/MatchlessToValue.scala, core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangGen.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala, core/src/test/scala/org/bykn/bosatsu/MatchlessTests.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala
This is so we can support multiple versions of packages simultaneously. The motivation here is to allow private dependencies in a library which don't have to be fixed to the same version as every transitive dependency.
The idea will be to make `(LibraryName, LibraryVersion)` as a `from` and then we can lookup in that context a PackageName which will tell you which `LibraryName, LibraryVersion` is in scope.
=> Add field to Matchless to show package source

core/src/main/scala/org/bykn/bosatsu/library/Command.scala, core/src/main/scala/org/bykn/bosatsu/library/DecodedLibrary.scala
the idea here is that we can load the fully materialized set of transitive libraries and what they all see.
Then, when compiling from matchless to C (or python) we can link the correct matchless value for each item.
=> Add DecodedLibraryWithDeps

cli/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala, cli/src/test/scala/org/bykn/bosatsu/codegen/python/PythonGenTest.scala, core/.js/src/main/scala/org/bykn/bosatsu/Par.scala, core/.jvm/src/main/scala/org/bykn/bosatsu/Par.scala, core/src/main/scala/org/bykn/bosatsu/MainModule.scala, core/src/main/scala/org/bykn/bosatsu/codegen/CompilationNamespace.scala, core/src/main/scala/org/bykn/bosatsu/codegen/CompilationSource.scala, core/src/main/scala/org/bykn/bosatsu/codegen/Transpiler.scala, core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangGen.scala, core/src/main/scala/org/bykn/bosatsu/codegen/clang/ClangTranspiler.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonGen.scala, core/src/main/scala/org/bykn/bosatsu/codegen/python/PythonTranspiler.scala, core/src/main/scala/org/bykn/bosatsu/graph/Dag.scala, core/src/main/scala/org/bykn/bosatsu/graph/Toposort.scala, core/src/test/scala/org/bykn/bosatsu/TestUtils.scala, core/src/test/scala/org/bykn/bosatsu/codegen/clang/ClangGenTest.scala, core/src/test/scala/org/bykn/bosatsu/graph/DagTest.scala, core/src/test/scala/org/bykn/bosatsu/graph/ToposortTest.scala
The idea here is to have an interface abstract over all the questions we ask of compiling a collection of code. This should support the previous way of "one world" for all packages, vs the "multiverse" approach of libraries having public and private dependencies and not forcing a resolution to a single version of all transitive libraries.
=> Use CompilationNamespace to abstract over Libraries vs stand-alone
